"""multi_tenant

Revision ID: 00000003
Revises: 00000002
Create Date: 2023-07-09 08:43:15.401142

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from mapa.core.data.base_entity import NULL_TENANT_ID


# revision identifiers, used by Alembic.
revision = '00000003'
down_revision = '00000002'
branch_labels = None
depends_on = None

table_list = ["app", "content_page"]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('translation', sa.JSON(), nullable=True), schema='application')
    # ### end Alembic commands ###
    
    # tenant_isolation
    execute_tenant_isolation("application", table_list, enable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'translation', schema='application')
    
    # ### end Alembic commands ###

    # tenant_isolation
    down_list = table_list.copy()
    down_list.reverse()
    execute_tenant_isolation("application", down_list, enable=False)


def execute_tenant_isolation(schema, tables, enable):
    for table in tables:
        full_name = f"{schema}.{table}"
        if enable:
            op.execute( f"alter table {full_name} enable row level security")
            op.execute( f"create policy tenant_isolation_insert on {full_name} "
                        f"for INSERT "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_select on {full_name} "
                        f"for SELECT "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text) OR ((tenant_id)::text = '{str(NULL_TENANT_ID)}'))"
                        )
            op.execute( f"create policy tenant_isolation_update on {full_name} "
                        f"for UPDATE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text)) "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_delete on {full_name} "
                        f"for DELETE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text))"
                        )
        else:
            op.execute(f"drop policy tenant_isolation_insert on {full_name}")
            op.execute(f"drop policy tenant_isolation_select on {full_name}")
            op.execute(f"drop policy tenant_isolation_update on {full_name}")
            op.execute(f"drop policy tenant_isolation_delete on {full_name}")
            op.execute(f"alter table {full_name} disable row level security")
        
        