"""application_order

Revision ID: 00000006
Revises: 00000005
Create Date: 2023-08-03 09:22:38.406965

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from mapa.application.app.app_entity import AppEntity


# revision identifiers, used by Alembic.
revision = '00000006'
down_revision = '00000005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('ordr', sa.Numeric(),
                  nullable=True), schema='application')
    op.execute(
        AppEntity.__table__.update().values(
            ordr=op.inline_literal(1))
    )
    op.alter_column('app', 'ordr',
                    existing_type=sa.NUMERIC(),
                    nullable=False,
                    schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'ordr', schema='application')
    # ### end Alembic commands ###
