"""init application

Revision ID: 00000001
Revises: 
Create Date: 2023-03-05 06:28:16.477688

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    
    op.execute("CREATE SCHEMA IF NOT EXISTS application")
    op.execute("GRANT USAGE ON SCHEMA application TO mapa")
    op.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mapa")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('menu', sa.JSON(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('api_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('logout_uri', sa.Text(), nullable=True),
    sa.Column('return_uri', sa.Text(), nullable=True),
    sa.Column('client_secret', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='app_uk_1'),
    schema=sa.quoted_name("application", True)
    )
    op.create_index(op.f('ix_application_app_api_id'), 'app', ['api_id'], unique=False, schema='application')
    op.create_index(op.f('ix_application_app_client_id'), 'app', ['client_id'], unique=False, schema='application')
    op.create_index(op.f('ix_application_app_tenant_id'), 'app', ['tenant_id'], unique=False, schema='application')
    op.create_table('content_page',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('designer_schema', sa.JSON(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('app_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['application.app.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='content_page_uk_1'),
    schema='application'
    )
    op.create_index(op.f('ix_application_content_page_app_id'), 'content_page', ['app_id'], unique=False, schema='application')
    op.create_index(op.f('ix_application_content_page_tenant_id'), 'content_page', ['tenant_id'], unique=False, schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_content_page_tenant_id'), table_name='content_page', schema='application')
    op.drop_index(op.f('ix_application_content_page_app_id'), table_name='content_page', schema='application')
    op.drop_table('content_page', schema='application')
    op.drop_index(op.f('ix_application_app_tenant_id'), table_name='app', schema='application')
    op.drop_index(op.f('ix_application_app_client_id'), table_name='app', schema='application')
    op.drop_index(op.f('ix_application_app_api_id'), table_name='app', schema='application')
    op.drop_table('app', schema='application')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS application")