"""application_code

Revision ID: 00000007
Revises: 00000006
Create Date: 2023-08-17 12:26:20.667451

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from mapa.application.app.app_entity import AppEntity


# revision identifiers, used by Alembic.
revision = '00000007'
down_revision = '00000006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('code', sa.Text(), nullable=True), schema='application')
    op.execute("UPDATE application.app SET code = name")
    op.alter_column('app', 'code',
                    existing_type=sa.Text(),
                    nullable=False,
                    schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'code', schema='application')
    # ### end Alembic commands ###
