"""tenant id güncellemesi

Revision ID: 00000002
Revises: 00000001
Create Date: 2023-03-05 12:24:21.629722

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00000002'
down_revision = '00000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app', 'tenant_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='application')
    op.drop_constraint('app_uk_1', 'app', schema='application', type_='unique')
    op.create_unique_constraint('app_uk_1', 'app', ['name', 'tenant_id'], schema='application')
    op.drop_constraint('content_page_uk_1', 'content_page', schema='application', type_='unique')
    op.create_unique_constraint('content_page_uk_1', 'content_page', ['name', 'app_id'], schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('content_page_uk_1', 'content_page', schema='application', type_='unique')
    op.create_unique_constraint('content_page_uk_1', 'content_page', ['name'], schema='application')
    op.drop_constraint('app_uk_1', 'app', schema='application', type_='unique')
    op.create_unique_constraint('app_uk_1', 'app', ['name'], schema='application')
    op.alter_column('app', 'tenant_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               schema='application')
    # ### end Alembic commands ###
