"""content_page_scope_nullable

Revision ID: 00000005
Revises: 00000004
Create Date: 2023-07-11 13:13:12.691718

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000005'
down_revision = '00000004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_page', 'scope',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_page', 'scope',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='application')
    # ### end Alembic commands ###
