"""connection_remove_columns

Revision ID: 00000011
Revises: 00000010
Create Date: 2023-11-06 19:49:32.703137

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000011'
down_revision = '00000010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'workspace_name', schema='spatial')
    op.drop_column('connection', 'map_service_type', schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('map_service_type', sa.TEXT(), autoincrement=False, nullable=False), schema='spatial')
    op.add_column('connection', sa.Column('workspace_name', sa.TEXT(), autoincrement=False, nullable=True), schema='spatial')
    # ### end Alembic commands ###
