"""layer_definiton_add_column

Revision ID: 00000010
Revises: 00000009
Create Date: 2023-10-23 14:08:28.947156

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa

from mapa.spatial.definition.definition_entity import DefinitionEntity
from mapa.spatial.layer.layer_entity import LayerEntity


# revision identifiers, used by Alembic.
revision = '00000010'
down_revision = '00000009'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('key_field', sa.Text(), nullable=True), schema='spatial')
    op.add_column('layer', sa.Column('key_field', sa.Text(), nullable=True), schema='spatial')
    
    
    op.execute(
        DefinitionEntity.__table__.update().where(
            DefinitionEntity.__table__.c.id is not None).values(
            key_field="id")
    )
    
    op.execute(
        LayerEntity.__table__.update().where(
            LayerEntity.__table__.c.id is not None).values(
            key_field="id")
    )
    
    op.alter_column('definition', 'key_field',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='spatial')
       
    op.alter_column('layer', 'key_field',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='spatial')
    
    op.drop_column('layer', 'type', schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True), schema='spatial')
    op.drop_column('layer', 'key_field', schema='spatial')
    op.drop_column('definition', 'key_field', schema='spatial')
    # ### end Alembic commands ###
