"""connection_add_column_type

Revision ID: 00000013
Revises: 00000012
Create Date: 2023-11-23 13:40:26.472325

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa

from mapa.spatial.connection.connection_entity import ConnectionEntity

# revision identifiers, used by Alembic.
revision = '00000013'
down_revision = '00000012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('type', sa.Text(), nullable=True), schema='spatial')
    op.execute(
        ConnectionEntity.__table__.update().where(
            ConnectionEntity.__table__.c.id is not None).values(
            type="External")
    )
    
    op.alter_column('connection', 'type',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'type', schema='spatial')
    # ### end Alembic commands ###
