"""update_layer_data

Revision ID: 00000014
Revises: 00000013
Create Date: 2024-01-04 12:18:53.633531

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy import (JSON,Uuid)

from mapa.spatial.layer.layer_entity import LayerEntity

# revision identifiers, used by Alembic.
revision = '00000014'
down_revision = '00000013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    layer_table = sa.Table('layer',
        sa.MetaData(schema='spatial'),
        sa.Column('id', Uuid(), primary_key=True),
        sa.Column('geometry_field_param', JSON, nullable=True))

    connection = op.get_bind()
    
    results = connection.execute(sa.select(
            layer_table.c.id,
            layer_table.c.geometry_field_param,
            )).fetchall()
    
    for id_, geometry_field_param in results:
        match geometry_field_param['type']:
            case "point":
                geometry_field_param['type'] = "Point"
            case "multipoint":
                geometry_field_param['type'] = "MultiPoint"
            case "polyline":
                geometry_field_param['type'] = "LineString"
            case "multipolyline":
                geometry_field_param['type'] = "MultiLineString"
            case "polygon":
                geometry_field_param['type'] = "Polygon"
            case "multipolygon":
                geometry_field_param['type'] = "MultiPolygon"
            case "geometry":
                geometry_field_param['type'] = "Geometry"
        
        connection.execute(layer_table.update().where(layer_table.c.id == id_).values(
            geometry_field_param = geometry_field_param
            ))
        
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
