"""map_add_column

Revision ID: 00000009
Revises: 00000008
Create Date: 2023-10-19 10:47:40.717663

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000009'
down_revision = '00000008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map', sa.Column('zoom', sa.Integer(), nullable=True), schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map', 'zoom', schema='spatial')
    # ### end Alembic commands ###
