"""layer-definition_add_column_type_name

Revision ID: 00000012
Revises: 00000011
Create Date: 2023-11-23 10:44:13.907633

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa

from mapa.spatial.definition.definition_entity import DefinitionEntity
from mapa.spatial.layer.layer_entity import LayerEntity

# revision identifiers, used by Alembic.
revision = '00000012'
down_revision = '00000011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('definition', sa.Column('type_name', sa.Text(), nullable=True), schema='spatial')
    op.add_column('layer', sa.Column('type_name', sa.Text(), nullable=True), schema='spatial')
    
    op.execute(
        DefinitionEntity.__table__.update().where(
            DefinitionEntity.__table__.c.id is not None).values(
            type_name="workspace_name:table_name")
    )
    
    op.execute(
        LayerEntity.__table__.update().where(
            LayerEntity.__table__.c.id is not None).values(
            type_name="workspace_name:table_name")
    )
    
    op.alter_column('definition', 'type_name',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='spatial')
       
    op.alter_column('layer', 'type_name',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='spatial')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'type_name', schema='spatial')
    op.drop_column('definition', 'type_name', schema='spatial')
    # ### end Alembic commands ###
