"""definition_add_column_org_geo_const

Revision ID: 00000016
Revises: 00000015
Create Date: 2024-05-02 07:52:38.577441

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000016'
down_revision = '00000015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('organization_geo_constraint', sa.Boolean(), nullable=True), schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('definition', 'organization_geo_constraint', schema='spatial')
    # ### end Alembic commands ###
