"""connection_add_column

Revision ID: 00000006
Revises: 00000005
Create Date: 2023-09-06 12:35:51.303034

"""
from datetime import date, datetime

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '00000006'
down_revision = '00000005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('workspace_name', sa.Text(), nullable=True), schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'workspace_name', schema='spatial')
    # ### end Alembic commands ###
