"""init_spatial

Revision ID: 00000001
Revises: 
Create Date: 2023-06-24 13:02:53.431864

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE SCHEMA IF NOT EXISTS spatial")
    op.execute("GRANT USAGE ON SCHEMA spatial TO mapa")
    op.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA spatial GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mapa")
     
    op.create_table('base_layer',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('type', sa.Text(), nullable=False),
                    sa.Column('connection', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='spatial'
                    )
    op.create_table('connection',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('route_params', sa.JSON(), nullable=False),
                    sa.Column('map_service_type', sa.Text(), nullable=False),
                    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', 'tenant_id',
                                        name='spatial_connection_uk_1'),
                    schema='spatial'
                    )
    op.create_index(op.f('ix_spatial_connection_tenant_id'), 'connection', [
                    'tenant_id'], unique=False, schema='spatial')
    op.create_table('definition',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=True),
                    sa.Column('title', sa.Text(), nullable=True),
                    sa.Column('default_extent', sa.Text(), nullable=True),
                    sa.Column('max_scale', sa.Integer(), nullable=True),
                    sa.Column('min_scale', sa.Integer(), nullable=True),
                    sa.Column('opacity', sa.Integer(), nullable=True),
                    sa.Column('timer', sa.Boolean(), nullable=True),
                    sa.Column('is_attribute_panel',
                              sa.Boolean(), nullable=True),
                    sa.Column('is_base_layer', sa.Boolean(), nullable=True),
                    sa.Column('field_params', sa.JSON(), nullable=True),
                    sa.Column('style_params', sa.JSON(), nullable=True),
                    sa.Column('topology_rules_params',
                              sa.JSON(), nullable=True),
                    sa.Column('filter_params', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='spatial'
                    )
    op.create_index(op.f('ix_spatial_definition_tenant_id'), 'definition', [
                    'tenant_id'], unique=False, schema='spatial')
    op.create_table('namespace',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('title', sa.Text(), nullable=True),
                    sa.Column('identifier', sa.Text(), nullable=False),
                    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', 'identifier', 'tenant_id',
                                        name='spatial_namespace_uk_1'),
                    schema='spatial'
                    )
    op.create_index(op.f('ix_spatial_namespace_tenant_id'), 'namespace', [
                    'tenant_id'], unique=False, schema='spatial')
    reference_table = op.create_table('reference',
                                      sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                                          binary=False), nullable=False),
                                      sa.Column('created_at',
                                                sa.DateTime(), nullable=True),
                                      sa.Column('epsgcode', sa.Text(),
                                                nullable=False),
                                      sa.Column('wkid', sa.Text(),
                                                nullable=False),
                                      sa.Column('wkt', sa.Text(),
                                                nullable=False),
                                      sa.Column('projcs', sa.Text(),
                                                nullable=False),
                                      sa.PrimaryKeyConstraint('id'),
                                      sa.UniqueConstraint(
                                          'epsgcode', name='spatial_reference_uk_1'),
                                      schema='spatial'
                                      )
    op.create_table('layer',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('code', sa.Text(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('title', sa.Text(), nullable=True),
                    sa.Column('type', sa.Text(), nullable=True),
                    sa.Column('default_extent', sa.Text(), nullable=True),
                    sa.Column('max_scale', sa.Integer(), nullable=True),
                    sa.Column('min_scale', sa.Integer(), nullable=True),
                    sa.Column('opacity', sa.Integer(), nullable=True),
                    sa.Column('timer', sa.Boolean(), nullable=True),
                    sa.Column('visible', sa.Boolean(), nullable=True),
                    sa.Column('field_params', sa.JSON(), nullable=True),
                    sa.Column('geometry_field_param',
                              sa.JSON(), nullable=True),
                    sa.Column('style_params', sa.JSON(), nullable=True),
                    sa.Column('connection_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['connection_id'], ['spatial.connection.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', 'connection_id',
                                        'tenant_id', name='spatial_layer_uk_1'),
                    schema='spatial'
                    )
    op.create_index(op.f('ix_spatial_layer_connection_id'), 'layer', [
                    'connection_id'], unique=False, schema='spatial')
    op.create_index(op.f('ix_spatial_layer_tenant_id'), 'layer', [
                    'tenant_id'], unique=False, schema='spatial')
    op.create_table('map',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('title', sa.Text(), nullable=True),
                    sa.Column('initial_extent', sa.Text(), nullable=False),
                    sa.Column('full_extent', sa.Text(), nullable=False),
                    sa.Column('widget_types', sa.JSON(), nullable=True),
                    sa.Column('namespace_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=True),
                    sa.Column('srid', sa.Text(), nullable=False),
                    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['namespace_id'], ['spatial.namespace.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', 'tenant_id',
                                        name='spatial_map_uk_1'),
                    schema='spatial'
                    )
    op.create_index(op.f('ix_spatial_map_tenant_id'), 'map', [
                    'tenant_id'], unique=False, schema='spatial')
    op.create_table('bookmark',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('location', sa.Text(), nullable=False),
                    sa.Column('thumbnail', sa.Text(), nullable=True),
                    sa.Column('map_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.ForeignKeyConstraint(['map_id'], ['spatial.map.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', 'map_id', 'user_id',
                                        name='spatial_bookmark_uk_1'),
                    schema='spatial'
                    )
    op.create_index(op.f('ix_spatial_bookmark_map_id'), 'bookmark', [
                    'map_id'], unique=False, schema='spatial')
    op.create_table('layer_definition',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('layer_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('definition_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=True),
                    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['definition_id'], ['spatial.definition.id'], ),
                    sa.ForeignKeyConstraint(
                        ['layer_id'], ['spatial.layer.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('layer_id', 'definition_id',
                                        'tenant_id', name='spatial_layer_definition_uk_1'),
                    schema='spatial'
                    )
    op.create_index(op.f('ix_spatial_layer_definition_layer_id'), 'layer_definition', [
                    'layer_id'], unique=False, schema='spatial')
    op.create_index(op.f('ix_spatial_layer_definition_tenant_id'), 'layer_definition', [
                    'tenant_id'], unique=False, schema='spatial')
    op.create_table('map_base_layer',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('order', sa.Integer(), nullable=False),
                    sa.Column('map_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('base_layer_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['base_layer_id'], ['spatial.base_layer.id'], ),
                    sa.ForeignKeyConstraint(['map_id'], ['spatial.map.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('map_id', 'base_layer_id',
                                        name='spatial_map_base_layer_uk_1'),
                    schema='spatial'
                    )
    op.create_index(op.f('ix_spatial_map_base_layer_base_layer_id'), 'map_base_layer', [
                    'base_layer_id'], unique=False, schema='spatial')
    op.create_index(op.f('ix_spatial_map_base_layer_map_id'), 'map_base_layer', [
                    'map_id'], unique=False, schema='spatial')
    op.create_table('map_layer',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('order', sa.Integer(), nullable=False),
                    sa.Column('parent_id', sa.Text(), nullable=True),
                    sa.Column('params', sa.JSON(), nullable=True),
                    sa.Column('map_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('layer_definition_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.ForeignKeyConstraint(['layer_definition_id'], [
                        'spatial.layer_definition.id'], ),
                    sa.ForeignKeyConstraint(['map_id'], ['spatial.map.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('map_id', 'layer_definition_id',
                                        'tenant_id', name='spatial_map_layer_uk_1'),
                    schema='spatial'
                    )
    op.create_index(op.f('ix_spatial_map_layer_layer_definition_id'), 'map_layer', [
                    'layer_definition_id'], unique=False, schema='spatial')
    op.create_index(op.f('ix_spatial_map_layer_map_id'), 'map_layer', [
                    'map_id'], unique=False, schema='spatial')
    op.create_index(op.f('ix_spatial_map_layer_tenant_id'), 'map_layer', [
                    'tenant_id'], unique=False, schema='spatial')
    # ### end Alembic commands ###

    op.bulk_insert(
        reference_table,  # type: ignore
        [
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea361", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:3857", 'wkid': "3857", 'wkt': 'PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Mercator_1SP"],PARAMETER["central_meridian",0],PARAMETER["scale_factor",1],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["X",EAST],AXIS["Y",NORTH],EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"],AUTHORITY["EPSG","3857"]]',   'projcs': "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea362", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:4230", 'wkid': "4230",
             'wkt': 'GEOGCS["ED50",DATUM["European_Datum_1950",SPHEROID["International 1924",6378388,297,AUTHORITY["EPSG","7022"]],TOWGS84[-87,-98,-121,0,0,0,0],AUTHORITY["EPSG","6230"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4230"]]',   'projcs': "+proj=longlat +ellps=intl +towgs84=-87,-98,-121,0,0,0,0 +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea363", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:4326", 'wkid': "4326",
             'wkt': 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]',   'projcs': "+proj=longlat +datum=WGS84 +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea364", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:5253", 'wkid': "5253",
             'wkt': 'PROJCS["TUREF / TM27",GEOGCS["TUREF",DATUM["Turkish_National_Reference_Frame",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","1057"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","5252"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",27],PARAMETER["scale_factor",1],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","5253"]]',   'projcs': "+proj=tmerc +lat_0=0 +lon_0=27 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea365", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:5254", 'wkid': "5254",
             'wkt': 'PROJCS["TUREF / TM30",GEOGCS["TUREF",DATUM["Turkish_National_Reference_Frame",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","1057"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","5252"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",30],PARAMETER["scale_factor",1],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","5254"]]',   'projcs': "+proj=tmerc +lat_0=0 +lon_0=30 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea366", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:5255", 'wkid': "5255",
             'wkt': 'PROJCS["TUREF / TM33",GEOGCS["TUREF",DATUM["Turkish_National_Reference_Frame",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","1057"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","5252"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",33],PARAMETER["scale_factor",1],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","5255"]]',   'projcs': "+proj=tmerc +lat_0=0 +lon_0=33 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea367", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:5256", 'wkid': "5256",
             'wkt': 'PROJCS["TUREF / TM36",GEOGCS["TUREF",DATUM["Turkish_National_Reference_Frame",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","1057"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","5252"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",36],PARAMETER["scale_factor",1],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","5256"]]',   'projcs': "+proj=tmerc +lat_0=0 +lon_0=36 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea368", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:5257", 'wkid': "5257",
             'wkt': 'PROJCS["TUREF / TM39",GEOGCS["TUREF",DATUM["Turkish_National_Reference_Frame",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","1057"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","5252"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",39],PARAMETER["scale_factor",1],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","5257"]]',   'projcs': "+proj=tmerc +lat_0=0 +lon_0=39 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea322", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:5258", 'wkid': "5258",
             'wkt': 'PROJCS["TUREF / TM42",GEOGCS["TUREF",DATUM["Turkish_National_Reference_Frame",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","1057"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","5252"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",42],PARAMETER["scale_factor",1],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","5258"]]',   'projcs': "+proj=tmerc +lat_0=0 +lon_0=42 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea333", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:5259", 'wkid': "5259",
             'wkt': 'PROJCS["TUREF / TM45",GEOGCS["TUREF",DATUM["Turkish_National_Reference_Frame",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","1057"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","5252"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",45],PARAMETER["scale_factor",1],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","5259"]]',   'projcs': "+proj=tmerc +lat_0=0 +lon_0=45 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea344", 'created_at': date(2023, 3, 2), 'epsgcode': "EPSG:32662", 'wkid': "32662",
             'wkt': 'PROJCS["WGS 84 / Plate Carree (deprecated)",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Equirectangular"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["X",EAST],AXIS["Y",NORTH],AUTHORITY["EPSG","32662"]]',   'projcs': "+proj=eqc +lat_ts=0 +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea355", 'created_at': date(2023, 3, 2), 'epsgcode': "ESRI:54001", 'wkid': "54001",
             'wkt': 'PROJCS["World_Plate_Carree",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["Degree",0.0174532925199433]],PROJECTION["Equirectangular"],PARAMETER["standard_parallel_1",0],PARAMETER["central_meridian",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["ESRI","54001"]]',   'projcs': "+proj=eqc +lat_ts=0 +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"},
            {'id': "d858b93d-5b5b-49b6-8302-9f96be0ea399", 'created_at': date(2023, 3, 2), 'epsgcode': "ESRI:104122", 'wkid': "104122",
             'wkt': 'GEOGCS["GCS_ITRF_1996",DATUM["International_Terrestrial_Reference_Frame_1996",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6654"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["ESRI","104122"]]',   'projcs': "+proj=longlat +ellps=GRS80 +no_defs"}
        ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spatial_map_layer_tenant_id'),
                  table_name='map_layer', schema='spatial')
    op.drop_index(op.f('ix_spatial_map_layer_map_id'),
                  table_name='map_layer', schema='spatial')
    op.drop_index(op.f('ix_spatial_map_layer_layer_definition_id'),
                  table_name='map_layer', schema='spatial')
    op.drop_table('map_layer', schema='spatial')
    op.drop_index(op.f('ix_spatial_map_base_layer_map_id'),
                  table_name='map_base_layer', schema='spatial')
    op.drop_index(op.f('ix_spatial_map_base_layer_base_layer_id'),
                  table_name='map_base_layer', schema='spatial')
    op.drop_table('map_base_layer', schema='spatial')
    op.drop_index(op.f('ix_spatial_layer_definition_tenant_id'),
                  table_name='layer_definition', schema='spatial')
    op.drop_index(op.f('ix_spatial_layer_definition_layer_id'),
                  table_name='layer_definition', schema='spatial')
    op.drop_table('layer_definition', schema='spatial')
    op.drop_index(op.f('ix_spatial_bookmark_map_id'),
                  table_name='bookmark', schema='spatial')
    op.drop_table('bookmark', schema='spatial')
    op.drop_index(op.f('ix_spatial_map_tenant_id'),
                  table_name='map', schema='spatial')
    op.drop_table('map', schema='spatial')
    op.drop_index(op.f('ix_spatial_layer_tenant_id'),
                  table_name='layer', schema='spatial')
    op.drop_index(op.f('ix_spatial_layer_connection_id'),
                  table_name='layer', schema='spatial')
    op.drop_table('layer', schema='spatial')
    op.drop_table('reference', schema='spatial')
    op.drop_index(op.f('ix_spatial_namespace_tenant_id'),
                  table_name='namespace', schema='spatial')
    op.drop_table('namespace', schema='spatial')
    op.drop_index(op.f('ix_spatial_definition_tenant_id'),
                  table_name='definition', schema='spatial')
    op.drop_table('definition', schema='spatial')
    op.drop_index(op.f('ix_spatial_connection_tenant_id'),
                  table_name='connection', schema='spatial')
    op.drop_table('connection', schema='spatial')
    op.drop_table('base_layer', schema='spatial')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS spatial")
