"""definition_add_column

Revision ID: 00000002
Revises: 00000001
Create Date: 2023-07-03 14:48:00.902545

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000002'
down_revision = '00000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('edit_snap_scale', sa.Integer(), nullable=True), schema='spatial')
    op.add_column('definition', sa.Column('data_type', sa.Text(), nullable=False), schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('definition', 'data_type', schema='spatial')
    op.drop_column('definition', 'edit_snap_scale', schema='spatial')
    # ### end Alembic commands ###
