"""add_tenant_column_and_multi_tenant

Revision ID: 00000004
Revises: 00000003
Create Date: 2023-07-11 06:24:32.476460

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, MetaData

from mapa.core.data.base_entity import NULL_TENANT_ID
from mapa.spatial.reference.reference_entity import ReferenceEntity

# revision identifiers, used by Alembic.
revision = '00000004'
down_revision = '00000003'
branch_labels = None
depends_on = None

table_list = [
    "base_layer",
    "bookmark",
    "map_base_layer",
    "reference",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_layer', sa.Column(
        'tenant_id', sa.Uuid(), nullable=True), schema='spatial')
    op.create_index(op.f('ix_spatial_base_layer_tenant_id'), 'base_layer', [
                    'tenant_id'], unique=False, schema='spatial')
    op.add_column('bookmark', sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
        binary=False), nullable=False), schema='spatial')
    op.drop_constraint('spatial_bookmark_uk_1', 'bookmark',
                       schema='spatial', type_='unique')
    op.create_unique_constraint('spatial_bookmark_uk_1', 'bookmark', [
                                'name', 'map_id', 'user_id', 'tenant_id'], schema='spatial')
    op.create_index(op.f('ix_spatial_bookmark_tenant_id'), 'bookmark', [
                    'tenant_id'], unique=False, schema='spatial')
    op.add_column('map_base_layer', sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
        binary=False), nullable=False), schema='spatial')
    op.drop_constraint('spatial_map_base_layer_uk_1',
                       'map_base_layer', schema='spatial', type_='unique')
    op.create_unique_constraint('spatial_map_base_layer_uk_1', 'map_base_layer', [
                                'map_id', 'base_layer_id', 'tenant_id'], schema='spatial')
    op.create_index(op.f('ix_spatial_map_base_layer_tenant_id'), 'map_base_layer', [
                    'tenant_id'], unique=False, schema='spatial')
    op.add_column('reference', sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
        binary=False), nullable=True), schema='spatial')
    op.drop_constraint('spatial_reference_uk_1', 'reference',
                       schema='spatial', type_='unique')
    op.create_unique_constraint('spatial_reference_uk_1', 'reference', [
                                'epsgcode', 'tenant_id'], schema='spatial')
    op.create_index(op.f('ix_spatial_reference_tenant_id'), 'reference', [
                    'tenant_id'], unique=False, schema='spatial')
    # ### end Alembic commands ###

    # reference update tenant_id
    op.execute(
        ReferenceEntity.__table__.update().values(
            tenant_id=op.inline_literal(str(NULL_TENANT_ID)))
    )

    op.alter_column('reference', 'tenant_id',
                    existing_type=sa.UUID(),
                    nullable=False,
                    schema='spatial')

    # tenant_isolation
    execute_tenant_isolation("spatial", table_list, enable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spatial_reference_tenant_id'),
                  table_name='reference', schema='spatial')
    op.drop_constraint('spatial_reference_uk_1', 'reference',
                       schema='spatial', type_='unique')
    op.create_unique_constraint('spatial_reference_uk_1', 'reference', [
                                'epsgcode'], schema='spatial')
    op.drop_column('reference', 'tenant_id', schema='spatial')
    op.drop_index(op.f('ix_spatial_map_base_layer_tenant_id'),
                  table_name='map_base_layer', schema='spatial')
    op.drop_constraint('spatial_map_base_layer_uk_1',
                       'map_base_layer', schema='spatial', type_='unique')
    op.create_unique_constraint('spatial_map_base_layer_uk_1', 'map_base_layer', [
                                'map_id', 'base_layer_id'], schema='spatial')
    op.drop_column('map_base_layer', 'tenant_id', schema='spatial')
    op.drop_index(op.f('ix_spatial_bookmark_tenant_id'),
                  table_name='bookmark', schema='spatial')
    op.drop_constraint('spatial_bookmark_uk_1', 'bookmark',
                       schema='spatial', type_='unique')
    op.create_unique_constraint('spatial_bookmark_uk_1', 'bookmark', [
                                'name', 'map_id', 'user_id'], schema='spatial')
    op.drop_column('bookmark', 'tenant_id', schema='spatial')
    op.drop_index(op.f('ix_spatial_base_layer_tenant_id'),
                  table_name='base_layer', schema='spatial')
    op.drop_column('base_layer', 'tenant_id', schema='spatial')
    # ### end Alembic commands ###

    # tenant_isolation
    down_list = table_list.copy()
    down_list.reverse()
    execute_tenant_isolation("spatial", down_list, enable=False)


def execute_tenant_isolation(schema, tables, enable):
    for table in tables:
        full_name = f"{schema}.{table}"
        if enable:
            op.execute(f"alter table {full_name} enable row level security")
            op.execute(f"create policy tenant_isolation_insert on {full_name} "
                       f"for INSERT "
                       f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                       )
            op.execute(f"create policy tenant_isolation_select on {full_name} "
                       f"for SELECT "
                       f"using  ((current_setting('app.tenant_id') = tenant_id::text) OR ((tenant_id)::text = '{str(NULL_TENANT_ID)}'))"
                       )
            op.execute(f"create policy tenant_isolation_update on {full_name} "
                       f"for UPDATE "
                       f"using  ((current_setting('app.tenant_id') = tenant_id::text)) "
                       f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                       )
            op.execute(f"create policy tenant_isolation_delete on {full_name} "
                       f"for DELETE "
                       f"using  ((current_setting('app.tenant_id') = tenant_id::text))"
                       )
        else:
            op.execute(f"drop policy tenant_isolation_insert on {full_name}")
            op.execute(f"drop policy tenant_isolation_select on {full_name}")
            op.execute(f"drop policy tenant_isolation_update on {full_name}")
            op.execute(f"drop policy tenant_isolation_delete on {full_name}")
            op.execute(f"alter table {full_name} disable row level security")
