"""layer_add_column_data_type

Revision ID: 00000005
Revises: 00000004
Create Date: 2023-07-12 06:33:48.826326

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000005'
down_revision = '00000004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('data_type', sa.Text(), nullable=False), schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'data_type', schema='spatial')
    # ### end Alembic commands ###
