"""layer_def_add_column_target_namespace

Revision ID: 00000017
Revises: 00000016
Create Date: 2024-06-27 11:50:59.902473

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000017'
down_revision = '00000016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('target_namespace', sa.Text(), nullable=True), schema='spatial')
    op.add_column('layer', sa.Column('target_namespace', sa.Text(), nullable=True), schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'target_namespace', schema='spatial')
    op.drop_column('definition', 'target_namespace', schema='spatial')
    # ### end Alembic commands ###
