"""layer_hook_update_unique_constraint

Revision ID: 00000018
Revises: 00000017
Create Date: 2024-07-09 13:03:01.783365

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000018'
down_revision = '00000017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('spatial_layer_hook_uk_1', 'layer_hook', schema='spatial', type_='unique')
    op.create_unique_constraint('spatial_layer_hook_uk_1', 'layer_hook', ['layer_definition_id', 'widget_name', 'hook_operation_type', 'tenant_id'], schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('spatial_layer_hook_uk_1', 'layer_hook', schema='spatial', type_='unique')
    op.create_unique_constraint('spatial_layer_hook_uk_1', 'layer_hook', ['layer_definition_id', 'route_id', 'tenant_id'], schema='spatial')
    # ### end Alembic commands ###
