"""layer_def_update

Revision ID: 00000008
Revises: 00000007
Create Date: 2023-09-15 10:03:38.530563

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000008'
down_revision = '00000007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('definition', 'opacity',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True,
               schema='spatial')
    op.alter_column('layer', 'opacity',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True,
               schema='spatial')
    op.alter_column('map_layer', 'layer_definition_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_layer', 'layer_definition_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='spatial')
    op.alter_column('layer', 'opacity',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='spatial')
    op.alter_column('definition', 'opacity',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='spatial')
    # ### end Alembic commands ###
