"""layer_column_type_change

Revision ID: 00000007
Revises: 00000006
Create Date: 2023-09-07 07:40:42.928195

"""
from datetime import date, datetime

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from mapa.spatial.definition.definition_entity import DefinitionEntity
from mapa.spatial.layer.layer_entity import LayerEntity

# revision identifiers, used by Alembic.
revision = '00000007'
down_revision = '00000006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute(
        DefinitionEntity.__table__.update().where(
            DefinitionEntity.__table__.c.opacity > 1).values(
            opacity=1)
    )
    
    op.execute(
        LayerEntity.__table__.update().where(
            LayerEntity.__table__.c.opacity > 1).values(
            opacity=1)
    )
    
    op.alter_column('definition', 'opacity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=1),
               existing_nullable=True,
               schema='spatial')
    op.alter_column('layer', 'opacity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=1),
               existing_nullable=True,
               schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layer', 'opacity',
               existing_type=sa.Float(precision=1),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='spatial')
    op.alter_column('definition', 'opacity',
               existing_type=sa.Float(precision=1),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='spatial')
    # ### end Alembic commands ###
