"""reference_add_column_name

Revision ID: 00000015
Revises: 00000014
Create Date: 2024-02-16 08:53:45.136558

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy import (JSON,Uuid,Text)
from mapa.spatial.reference.reference_entity import ReferenceEntity


# revision identifiers, used by Alembic.
revision = '00000015'
down_revision = '00000014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('reference', sa.Column('name', sa.Text(), nullable=True), schema='spatial')
    
    reference_table = sa.Table('reference',
        sa.MetaData(schema='spatial'),
        sa.Column('id', Uuid(), primary_key=True),
        sa.Column('epsgcode', Text, nullable=False),
        sa.Column('name', Text, nullable=False))
    connection = op.get_bind()
    
    results = connection.execute(sa.select(
            reference_table.c.id,
            reference_table.c.epsgcode,
            reference_table.c.name,
            )).fetchall()
    
    for id_, epsgcode, name in results:
        connection.execute(reference_table.update().where(reference_table.c.id == id_).values(
            name = epsgcode
            ))
     
    op.alter_column('reference', 'name', existing_type=sa.TEXT(), nullable=False, schema='spatial')
    op.create_unique_constraint('spatial_reference_uk_2', 'reference', ['name', 'tenant_id'], schema='spatial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('spatial_reference_uk_2', 'reference', schema='spatial', type_='unique')
    op.drop_column('reference', 'name', schema='spatial')
    # ### end Alembic commands ###
