"""add_table_hook_layer_hook

Revision ID: 00000003
Revises: 00000002
Create Date: 2023-07-05 07:46:35.730508

"""
import sqlalchemy_utils
from datetime import date
from datetime import datetime
from alembic import op
import sqlalchemy as sa

from mapa.core.data.base_entity import NULL_TENANT_ID

# revision identifiers, used by Alembic.
revision = '00000003'
down_revision = '00000002'
branch_labels = None
depends_on = None

table_list = [
    "namespace",
    "map_layer",
    "map",
    "connection",
    "layer",
    "definition",
    "layer_definition",
    "layer_hook"
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hook_table = op.create_table('hook',
                                 sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                                     binary=False), nullable=False),
                                 sa.Column('created_at',
                                           sa.DateTime(), nullable=True),
                                 sa.Column('type', sa.Text(), nullable=False),
                                 sa.Column('operation_type',
                                           sa.Text(), nullable=False),
                                 sa.Column('description', sa.Text(),
                                           nullable=True),
                                 sa.PrimaryKeyConstraint('id'),
                                 sa.UniqueConstraint('type', 'operation_type',
                                                     name='spatial_hook_uk_1'),
                                 schema='spatial'
                                 )
    op.create_table('layer_hook',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('route_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('layer_definition_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.Column('widget_name', sa.Text(), nullable=False),
                    sa.Column('hook_operation_type',
                              sa.Text(), nullable=False),
                    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), nullable=False),
                    sa.ForeignKeyConstraint(['layer_definition_id'], [
                        'spatial.layer_definition.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('layer_definition_id', 'route_id',
                                        'tenant_id', name='spatial_layer_hook_uk_1'),
                    schema='spatial'
                    )
    op.create_index(op.f('ix_spatial_layer_hook_tenant_id'), 'layer_hook', [
                    'tenant_id'], unique=False, schema='spatial')
    # ### end Alembic commands ###

    op.bulk_insert(
        hook_table,  # type: ignore
        [
            {
                'id': "d858b93d-5b5b-49b6-8302-9f96be0ea200",
                'created_at': date(2023, 6, 5),
                'type': "Layer",
                'operation_type': "GET",
                'description': 'sorgulama işlemi',
            },
            {
                'id': "d858b93d-5b5b-49b6-8302-9f96be0ea201",
                'created_at': date(2023, 6, 5),
                'type': "Layer",
                'operation_type': "POST",
                'description': 'ekleme işlemi',
            },
            {
                'id': "d858b93d-5b5b-49b6-8302-9f96be0ea202",
                'created_at': date(2023, 6, 5),
                'type': "Layer",
                'operation_type': "PUT",
                'description': 'güncelleme işlemi',
            },
            {
                'id': "d858b93d-5b5b-49b6-8302-9f96be0ea203",
                'created_at': date(2023, 6, 5),
                'type': "Layer",
                'operation_type': "DELETE",
                'description': 'silme işlemi',
            },
        ])


    # tenant_isolation
    execute_tenant_isolation("spatial", table_list, enable=True)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spatial_layer_hook_tenant_id'),
                  table_name='layer_hook', schema='spatial')
    op.drop_table('layer_hook', schema='spatial')
    op.drop_table('hook', schema='spatial')
    # ### end Alembic commands ###

    # tenant_isolation
    down_list = table_list.copy()
    down_list.reverse()
    execute_tenant_isolation("spatial", down_list, enable=False)


def execute_tenant_isolation(schema, tables, enable):
    for table in tables:
        full_name = f"{schema}.{table}"
        if enable:
            op.execute( f"alter table {full_name} enable row level security")
            op.execute( f"create policy tenant_isolation_insert on {full_name} "
                        f"for INSERT "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_select on {full_name} "
                        f"for SELECT "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text) OR ((tenant_id)::text = '{str(NULL_TENANT_ID)}'))"
                        )
            op.execute( f"create policy tenant_isolation_update on {full_name} "
                        f"for UPDATE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text)) "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_delete on {full_name} "
                        f"for DELETE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text))"
                        )
        else:
            op.execute(f"drop policy tenant_isolation_insert on {full_name}")
            op.execute(f"drop policy tenant_isolation_select on {full_name}")
            op.execute(f"drop policy tenant_isolation_update on {full_name}")
            op.execute(f"drop policy tenant_isolation_delete on {full_name}")
            op.execute(f"alter table {full_name} disable row level security")
