"""workspace_client_update

Revision ID: 00000009
Revises: 00000008
Create Date: 2023-08-03 20:28:58.353946

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from uuid import UUID

from mapa.manage.tenant_client.tenant_client_entity import TenantClientEntity


# revision identifiers, used by Alembic.
revision = '00000009'
down_revision = '00000008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute(
        TenantClientEntity.__table__.update().where(TenantClientEntity.__table__.c.id == op.inline_literal(
            "902e2038-acd1-4736-9a5a-f45e159b2c09")).values(client_id=op.inline_literal("891981ea-85ba-40bb-b150-409e339e5b65"))
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
