"""client_update

Revision ID: 00000007
Revises: 00000006
Create Date: 2023-07-28 18:40:44.796941

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, ARRAY
from sqlalchemy.sql import table, column

from mapa.manage.client.client_entity import ClientEntity

# revision identifiers, used by Alembic.
revision = '00000007'
down_revision = '00000006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        ClientEntity.__table__.update().where(
            ClientEntity.__table__.c.client_secret == op.inline_literal(
                "client_secret_manage")
        ).values(
            redirect_uris=op.inline_literal(
                "{http://localhost:33001/callback,http://localhost:33001/callback_silent,https://manage.kabart.com.tr/callback,https://manage.kabart.com.tr/callback_silent,https://test-manage.kabart.com.tr/callback,https://test-manage.kabart.com.tr/callback_silent}"))
    )

    op.execute(
        ClientEntity.__table__.update().where(
            ClientEntity.__table__.c.client_secret == op.inline_literal(
                "client_secret_gateway")
        ).values(
            redirect_uris=op.inline_literal(
                "{http://localhost:3003/callback,http://localhost:3003/callback_silent,https://application.kabart.com.tr/callback,https://application.kabart.com.tr/callback_silent,https://test-application.kabart.com.tr/callback,https://test-application.kabart.com.tr/callback_silent}"))
    )

    op.execute(
        ClientEntity.__table__.update().where(
            ClientEntity.__table__.c.client_secret == op.inline_literal(
                "client_secret_workspace")
        ).values(
            redirect_uris=op.inline_literal(
                "{http://localhost:33002/callback,http://localhost:33002/callback_silent,https://workspace.kabart.com.tr/callback,https://workspace.kabart.com.tr/callback_silent,https://test-workspace.kabart.com.tr/callback,https://test-workspace.kabart.com.tr/callback_silent}"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
