"""organization_add_geo_column

Revision ID: 00000014
Revises: 00000013
Create Date: 2024-04-29 14:19:20.823604

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000014'
down_revision = '00000013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('geo', sa.JSON(), nullable=True), schema='manage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'geo', schema='manage')
    # ### end Alembic commands ###
