"""manage user cascade eklendi

Revision ID: 00000003
Revises: 00000002
Create Date: 2023-03-06 17:38:19.763778

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000003'
down_revision = '00000002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenant_user_id_fkey', 'tenant', schema='manage', type_='foreignkey')
    op.create_foreign_key(None, 'tenant', 'user', ['user_id'], ['id'], source_schema='manage', referent_schema='manage', ondelete='CASCADE')
    op.drop_constraint('tenant_user_user_id_fkey', 'tenant_user', schema='manage', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_user', 'user', ['user_id'], ['id'], source_schema='manage', referent_schema='manage', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_user', schema='manage', type_='foreignkey')
    op.create_foreign_key('tenant_user_user_id_fkey', 'tenant_user', 'user', ['user_id'], ['id'], source_schema='manage', referent_schema='manage')
    op.drop_constraint(None, 'tenant', schema='manage', type_='foreignkey')
    op.create_foreign_key('tenant_user_id_fkey', 'tenant', 'user', ['user_id'], ['id'], source_schema='manage', referent_schema='manage')
    # ### end Alembic commands ###
