"""invitation_add_uk

Revision ID: 00000010
Revises: 00000009
Create Date: 2024-02-16 14:04:32.169127

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000010'
down_revision = '00000009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE manage.invitation DROP CONSTRAINT IF EXISTS invitation_uk_1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE manage.invitation DROP CONSTRAINT IF EXISTS invitation_uk_1")
    # ### end Alembic commands ###
