"""organization_islemleri

Revision ID: 00000011
Revises: 00000010
Create Date: 2024-02-29 11:39:18.779234

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func
from sqlalchemy import (JSON,Uuid,Text,DateTime,Boolean)
from mapa.manage.api_scope.api_scope_entity import ApiScopeEntity
from mapa.manage.role_api_scope.role_api_scope_entity import RoleApiScopeEntity
from mapa.core.data.base_entity import NULL_TENANT_ID
from uuid import UUID, uuid4
from datetime import datetime, timedelta


# revision identifiers, used by Alembic.
revision = '00000011'
down_revision = '00000010'
branch_labels = None
depends_on = None


delete_role_api_scope_list = [
    "acd02959-c73a-4b5b-8395-c452d6970123",
    "acd02959-c73a-4b5b-8395-c452d6970124",
    "acd02959-c73a-4b5b-8395-c452d6970125",
    "acd02959-c73a-4b5b-8395-c452d6970126",
    "acd02959-c73a-4b5b-8395-c452d6970127",
    "acd02959-c73a-4b5b-8395-c452d6970128",
    "acd02959-c73a-4b5b-8395-c452d6970129",
    "acd02959-c73a-4b5b-8395-c452d6970130",
]

delete_api_scope_list = [
    "932a5e98-0003-4c46-aa03-770679bd0123",
    "932a5e98-0003-4c46-aa03-770679bd0124",
    "932a5e98-0003-4c46-aa03-770679bd0125",
    "932a5e98-0003-4c46-aa03-770679bd0126",
    "932a5e98-0003-4c46-aa03-770679bd0127",
    "932a5e98-0003-4c46-aa03-770679bd0128",
    "932a5e98-0003-4c46-aa03-770679bd0129",
    "932a5e98-0003-4c46-aa03-770679bd0130",
]

table_list = [
    "organization",
    "organization_type",
    "organization_user",
    "organization_role"
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute("ALTER TABLE manage.invitation DROP CONSTRAINT IF EXISTS invitation_uk_1")
    
    # organization - organization_type - organization_user - organization_role  tabloları için scope tanımları
    op.bulk_insert(
        ApiScopeEntity.__table__,  # type: ignore
        [
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0123",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:organization",
                "description": "Query of organization",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0124",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:organization",
                "description": "Edit of organization",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0125",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:organization_user",
                "description": "Query of organization user",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            }, 
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0126",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:organization_user",
                "description": "Edit of organization user",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0127",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:organization_type",
                "description": "Query of organization type",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0128",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:organization_type",
                "description": "Edit of organization type",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0129",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:organization_role",
                "description": "Query of organization role",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0130",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:organization_role",
                "description": "Edit of organization role",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },  
        ]
    )   

    op.bulk_insert(
        RoleApiScopeEntity.__table__,  # type: ignore
        [
             {
                "id": "acd02959-c73a-4b5b-8395-c452d6970123",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0123",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "acd02959-c73a-4b5b-8395-c452d6970124",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0124",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "acd02959-c73a-4b5b-8395-c452d6970125",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0125",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "acd02959-c73a-4b5b-8395-c452d6970126",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0126",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "acd02959-c73a-4b5b-8395-c452d6970127",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0127",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "acd02959-c73a-4b5b-8395-c452d6970128",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0128",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "acd02959-c73a-4b5b-8395-c452d6970129",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0129",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "acd02959-c73a-4b5b-8395-c452d6970130",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0130",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
        ]
    )
    # end of organization - organization_type - organization_user - organization_role tabloları için scope tanımları
    
    
    op.create_table('organization_type',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tenant_id', name='organization_type_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_organization_type_name'), 'organization_type', ['name'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_organization_type_parent_id'), 'organization_type', ['parent_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_organization_type_tenant_id'), 'organization_type', ['tenant_id'], unique=False, schema='manage')
    op.create_table('organization',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('is_hierarchical', sa.Boolean(), nullable=True),
    sa.Column('integration_id', sa.Text(), nullable=True),
    sa.Column('organization_type_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_type_id'], ['manage.organization_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tenant_id', name='organization_uk_1'),
    sa.UniqueConstraint('tenant_id', 'integration_id', name='organization_uk_2'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_organization_name'), 'organization', ['name'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_organization_parent_id'), 'organization', ['parent_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_organization_tenant_id'), 'organization', ['tenant_id'], unique=False, schema='manage')
    op.create_table('organization_role',
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('role_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['manage.organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['manage.role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'organization_id', 'tenant_id', name='organization_role_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_organization_role_organization_id'), 'organization_role', ['organization_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_organization_role_role_id'), 'organization_role', ['role_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_organization_role_tenant_id'), 'organization_role', ['tenant_id'], unique=False, schema='manage')
    op.create_table('organization_user',
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['manage.organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['manage.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', 'tenant_id', name='organization_user_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_organization_user_organization_id'), 'organization_user', ['organization_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_organization_user_tenant_id'), 'organization_user', ['tenant_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_organization_user_user_id'), 'organization_user', ['user_id'], unique=False, schema='manage')
    op.add_column('invitation', sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True), schema='manage')
    op.create_unique_constraint('invitation_uk_1', 'invitation', ['email', 'tenant', 'organization_id'], schema='manage')
    op.create_foreign_key(None, 'invitation', 'organization', ['organization_id'], ['id'], source_schema='manage', referent_schema='manage', ondelete='SET NULL')
    
    
    organization_type_table = sa.Table('organization_type',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True),
        sa.Column('name', Text, nullable=False),
        sa.Column('description', Text, nullable=True),
        sa.Column('is_root', Text, nullable=False),
        sa.Column('tenant_id', Uuid(), nullable=False),
        sa.Column('created_at', DateTime,default=func.now()))
      
    organization_table = sa.Table('organization',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True),
        sa.Column('name', Text, nullable=False),
        sa.Column('description', Text, nullable=True),
        sa.Column('is_root', Text, nullable=False),
        sa.Column('tenant_id', Uuid(), nullable=False),
        sa.Column('organization_type_id', Uuid(), nullable=False),
        sa.Column('is_hierarchical', Boolean, nullable=True),
        sa.Column('created_at', DateTime,default=func.now()))
    
    organization_user_table = sa.Table('organization_user',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True),
        sa.Column('user_id', Uuid(), nullable=False),
        sa.Column('organization_id', Uuid(), nullable=False),
        sa.Column('created_at', DateTime,default=func.now()),
        sa.Column('tenant_id', Uuid(), nullable=False))
    
    tenant_table = sa.Table('tenant',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True),
        sa.Column('user_id', Text, nullable=False),
        sa.Column('title', Text, nullable=True),
        sa.Column('name', Text, nullable=False))
    
    tenant_user_table = sa.Table('tenant_user',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True),
        sa.Column('tenant_id', Uuid(), nullable=False),
        sa.Column('user_id', Uuid(), nullable=False),
        sa.Column('role', Text, nullable=False))
    
    invitation_table = sa.Table('invitation',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True),
        sa.Column('email',Text, nullable=False),
        sa.Column('user_id', Uuid(), nullable=False),
        sa.Column('organization_id', Uuid(), nullable=False),
        sa.Column('tenant', Uuid(), nullable=False))
    
    connection = op.get_bind()
    
    tenants = connection.execute(sa.select(
        tenant_table.c.id,
        tenant_table.c.user_id,
        tenant_table.c.name,
        tenant_table.c.title,
        )).fetchall()

    for id, user_id, name,title in tenants:
        organization_type_id: UUID = uuid4()
        organization_id: UUID = uuid4()
        organization_user_id: UUID = uuid4()
        connection.execute(organization_type_table.insert().values(id=organization_type_id,name=name,description=title,is_root=True,tenant_id=id,created_at=func.now()))
        connection.execute(organization_table.insert().values(id=organization_id,is_hierarchical=True,organization_type_id=organization_type_id,name=name,description=title,is_root=True,tenant_id=id,created_at=func.now()))
        connection.execute(organization_user_table.insert().values(id=organization_user_id,tenant_id=id,organization_id=organization_id,user_id=user_id,created_at=func.now()))
    
    tenant_users = connection.execute(sa.select(
            tenant_user_table.c.id,
            tenant_user_table.c.tenant_id,
            tenant_user_table.c.user_id,
            tenant_user_table.c.role,
            ).where(tenant_user_table.c.role == 'member')).fetchall()
    
    for id, tenant_id, user_id, role in tenant_users:
        second_organizations = connection.execute(sa.select(
            organization_table.c.id,
            organization_table.c.name,
            organization_table.c.tenant_id,
            ).where(organization_table.c.tenant_id == tenant_id)).fetchall()
        for id_, name, tenant_id_ in second_organizations:    
            organization_user_id: UUID = uuid4()
            connection.execute(organization_user_table.insert().values(id=organization_user_id,tenant_id=tenant_id_,organization_id=id_,user_id=user_id,created_at=func.now()))
            connection.execute(invitation_table.update().where(invitation_table.c.tenant == tenant_id_).values(organization_id=id_))
    
    # tenant_isolation
    execute_tenant_isolation("manage", table_list, enable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
      
    # tenant_isolation
    down_list = table_list.copy()
    down_list.reverse()
    execute_tenant_isolation("manage", down_list, enable=False)
    
    # organization - organization_type - organization_user - organization_role  tabloları için scope tanımları kaldırılır
    role_api_scope_table = sa.Table('role_api_scope',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True))
    connection = op.get_bind()
    
    for id_ in delete_role_api_scope_list:
        connection.execute(role_api_scope_table.delete().where(role_api_scope_table.c.id == id_))
    
        
    api_scope_table = sa.Table('api_scope',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True))
    connection = op.get_bind()
    
    for id_ in delete_api_scope_list:
        connection.execute(api_scope_table.delete().where(api_scope_table.c.id == id_))
    # end of organization - organization_type - organization_user - organization_role tabloları için scope tanımları kaldırılır
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invitation_uk_1', 'invitation', schema='manage', type_='unique')
    op.drop_column('invitation', 'organization_id', schema='manage')
    op.drop_index(op.f('ix_manage_organization_user_user_id'), table_name='organization_user', schema='manage')
    op.drop_index(op.f('ix_manage_organization_user_tenant_id'), table_name='organization_user', schema='manage')
    op.drop_index(op.f('ix_manage_organization_user_organization_id'), table_name='organization_user', schema='manage')
    op.drop_table('organization_user', schema='manage')
    op.drop_index(op.f('ix_manage_organization_role_tenant_id'), table_name='organization_role', schema='manage')
    op.drop_index(op.f('ix_manage_organization_role_role_id'), table_name='organization_role', schema='manage')
    op.drop_index(op.f('ix_manage_organization_role_organization_id'), table_name='organization_role', schema='manage')
    op.drop_table('organization_role', schema='manage')
    op.drop_index(op.f('ix_manage_organization_tenant_id'), table_name='organization', schema='manage')
    op.drop_index(op.f('ix_manage_organization_parent_id'), table_name='organization', schema='manage')
    op.drop_index(op.f('ix_manage_organization_name'), table_name='organization', schema='manage')
    op.drop_table('organization', schema='manage')
    op.drop_index(op.f('ix_manage_organization_type_tenant_id'), table_name='organization_type', schema='manage')
    op.drop_index(op.f('ix_manage_organization_type_parent_id'), table_name='organization_type', schema='manage')
    op.drop_index(op.f('ix_manage_organization_type_name'), table_name='organization_type', schema='manage')
    op.drop_table('organization_type', schema='manage')
  
    # ### end Alembic commands ###



def execute_tenant_isolation(schema, tables, enable):
    for table in tables:
        full_name = f"{schema}.{table}"
        if enable:
            op.execute( f"alter table {full_name} enable row level security")
            op.execute( f"create policy tenant_isolation_insert on {full_name} "
                        f"for INSERT "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_select on {full_name} "
                        f"for SELECT "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text) OR ((tenant_id)::text = '{str(NULL_TENANT_ID)}'))"
                        )
            op.execute( f"create policy tenant_isolation_update on {full_name} "
                        f"for UPDATE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text)) "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_delete on {full_name} "
                        f"for DELETE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text))"
                        )
        else:
            op.execute(f"drop policy tenant_isolation_insert on {full_name}")
            op.execute(f"drop policy tenant_isolation_select on {full_name}")
            op.execute(f"drop policy tenant_isolation_update on {full_name}")
            op.execute(f"drop policy tenant_isolation_delete on {full_name}")
            op.execute(f"alter table {full_name} disable row level security")