"""organization_client_iliskisi

Revision ID: 00000012
Revises: 00000011
Create Date: 2024-03-06 13:48:08.401350

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func
from sqlalchemy import (JSON,Uuid,Text,DateTime,Boolean)
from mapa.manage.api_scope.api_scope_entity import ApiScopeEntity
from mapa.manage.role_api_scope.role_api_scope_entity import RoleApiScopeEntity
from mapa.core.data.base_entity import NULL_TENANT_ID


# revision identifiers, used by Alembic.
revision = '00000012'
down_revision = '00000011'
branch_labels = None
depends_on = None

delete_role_api_scope_list = [
    "acd02959-c73a-4b5b-8395-c452d6970131",
    "acd02959-c73a-4b5b-8395-c452d6970132",
]

delete_api_scope_list = [
    "932a5e98-0003-4c46-aa03-770679bd0131",
    "932a5e98-0003-4c46-aa03-770679bd0132",
]

table_list = [
    "organization_client"
]

def upgrade() -> None:
    
    # organization_client tabloları için scope tanımları
    op.bulk_insert(
        ApiScopeEntity.__table__,  # type: ignore
        [
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0131",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:organization_client",
                "description": "Query of organization client",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0132",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:organization_client",
                "description": "Edit of organization client",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            }
        ]
    )   

    op.bulk_insert(
        RoleApiScopeEntity.__table__,  # type: ignore
        [
             {
                "id": "acd02959-c73a-4b5b-8395-c452d6970131",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0131",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "acd02959-c73a-4b5b-8395-c452d6970132",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0132",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            }
        ]
    )
    # end of organization_client tabloları için scope tanımları
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_client',
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('is_hierarchical', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['manage.client.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['manage.organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'organization_id', 'tenant_id', name='organization_client_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_organization_client_client_id'), 'organization_client', ['client_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_organization_client_organization_id'), 'organization_client', ['organization_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_organization_client_tenant_id'), 'organization_client', ['tenant_id'], unique=False, schema='manage')
    # ### end Alembic commands ###

    # tenant_isolation
    execute_tenant_isolation("manage", table_list, enable=True)

def downgrade() -> None:
    
    # tenant_isolation
    down_list = table_list.copy()
    down_list.reverse()
    execute_tenant_isolation("manage", down_list, enable=False)
    
    # organization_client tabloları için scope tanımları kaldırılır
    role_api_scope_table = sa.Table('role_api_scope',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True))
    connection = op.get_bind()
    
    for id_ in delete_role_api_scope_list:
        connection.execute(role_api_scope_table.delete().where(role_api_scope_table.c.id == id_))
    
        
    api_scope_table = sa.Table('api_scope',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True))
    connection = op.get_bind()
    
    for id_ in delete_api_scope_list:
        connection.execute(api_scope_table.delete().where(api_scope_table.c.id == id_))
    # end of organization_client tabloları için scope tanımları kaldırılır
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manage_organization_client_tenant_id'), table_name='organization_client', schema='manage')
    op.drop_index(op.f('ix_manage_organization_client_organization_id'), table_name='organization_client', schema='manage')
    op.drop_index(op.f('ix_manage_organization_client_client_id'), table_name='organization_client', schema='manage')
    op.drop_table('organization_client', schema='manage')
    # ### end Alembic commands ###


def execute_tenant_isolation(schema, tables, enable):
    for table in tables:
        full_name = f"{schema}.{table}"
        if enable:
            op.execute( f"alter table {full_name} enable row level security")
            op.execute( f"create policy tenant_isolation_insert on {full_name} "
                        f"for INSERT "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_select on {full_name} "
                        f"for SELECT "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text) OR ((tenant_id)::text = '{str(NULL_TENANT_ID)}'))"
                        )
            op.execute( f"create policy tenant_isolation_update on {full_name} "
                        f"for UPDATE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text)) "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_delete on {full_name} "
                        f"for DELETE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text))"
                        )
        else:
            op.execute(f"drop policy tenant_isolation_insert on {full_name}")
            op.execute(f"drop policy tenant_isolation_select on {full_name}")
            op.execute(f"drop policy tenant_isolation_update on {full_name}")
            op.execute(f"drop policy tenant_isolation_delete on {full_name}")
            op.execute(f"alter table {full_name} disable row level security")