"""init manage

Revision ID: 00000001
Revises: 
Create Date: 2023-03-02 15:49:39.445362

"""
from datetime import date
from datetime import datetime
from psycopg2 import Timestamp
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    
    op.execute("CREATE SCHEMA IF NOT EXISTS manage")
    op.execute("GRANT USAGE ON SCHEMA manage TO mapa")
    op.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA manage GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mapa")
    
    # ### commands auto generated by Alembic - please adjust! ###
    api_table = op.create_table('api',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('allow_offline_access', sa.Boolean(), nullable=True),
    sa.Column('skip_consent_for_verifiable_first_party_clients', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('token_lifetime', sa.Integer(), nullable=True),
    sa.Column('token_lifetime_for_web', sa.Integer(), nullable=True),
    sa.Column('signing_alg', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('level_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', name='api_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_api_tenant_id'), 'api', ['tenant_id'], unique=False, schema='manage')
    client_table = op.create_table('client',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('client_secret', sa.Text(), nullable=False),
    sa.Column('grant_types', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('redirect_uris', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('logout_uris', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('client_uri', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_type', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('token_endpoint_auth_method', sa.Text(), nullable=True),
    sa.Column('web_origins', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('cors_origins', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('require_consent', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('require_pkce', sa.Boolean(), nullable=True),
    sa.Column('level_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='client_uk_1'),
    sa.UniqueConstraint('client_secret', name='client_uk_2'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_client_client_id'), 'client', ['client_id'], unique=False, schema='manage')
    op.create_table('invitation',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_invitation_tenant_id'), 'invitation', ['tenant_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_invitation_user_id'), 'invitation', ['user_id'], unique=False, schema='manage')
    op.create_table('profile_adaptor',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('user_info_endpoint', sa.Text(), nullable=False),
    sa.Column('user_info_list_endpoint', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_profile_adaptor_tenant_id'), 'profile_adaptor', ['tenant_id'], unique=False, schema='manage')
    op.create_table('role',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_role_name'), 'role', ['name'], unique=True, schema='manage')
    op.create_index(op.f('ix_manage_role_tenant_id'), 'role', ['tenant_id'], unique=False, schema='manage')
    user_table = op.create_table('user',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('surname', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('last_tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('provider_user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('profile_adaptor_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('openid', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('given_name', sa.Text(), nullable=True),
    sa.Column('family_name', sa.Text(), nullable=True),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('offline_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_user_email'), 'user', ['email'], unique=True, schema='manage')
    op.create_index(op.f('ix_manage_user_subject_id'), 'user', ['subject_id'], unique=True, schema='manage')
    op.create_table('api_scope',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('api_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['manage.api.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='api_scope_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_api_scope_tenant_id'), 'api_scope', ['tenant_id'], unique=False, schema='manage')
    client_api_table = op.create_table('client_api',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('api_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('client_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['manage.api.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['manage.client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id', 'client_id', name='client_api_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_client_api_api_id'), 'client_api', ['api_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_client_api_client_id'), 'client_api', ['client_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_client_api_tenant_id'), 'client_api', ['tenant_id'], unique=False, schema='manage')
    op.create_table('role_user',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('role_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['manage.role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['manage.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='role_user_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_role_user_role_id'), 'role_user', ['role_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_role_user_tenant_id'), 'role_user', ['tenant_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_role_user_user_id'), 'role_user', ['user_id'], unique=False, schema='manage')
    tenant_table = op.create_table('tenant',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('session_timeout', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['manage.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='manage'
    )
    tenant_client_table =  op.create_table('tenant_client',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('client_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['manage.client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_tenant_client_client_id'), 'tenant_client', ['client_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_tenant_client_tenant_id'), 'tenant_client', ['tenant_id'], unique=False, schema='manage')
    tenant_user_table = op.create_table('tenant_user',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('tenant', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['manage.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_tenant_user_tenant'), 'tenant_user', ['tenant'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_tenant_user_user_id'), 'tenant_user', ['user_id'], unique=False, schema='manage')
    op.create_table('client_api_scope',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('api_scope_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('client_api_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['api_scope_id'], ['manage.api_scope.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_api_id'], ['manage.client_api.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_client_api_scope_api_scope_id'), 'client_api_scope', ['api_scope_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_client_api_scope_client_api_id'), 'client_api_scope', ['client_api_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_client_api_scope_tenant_id'), 'client_api_scope', ['tenant_id'], unique=False, schema='manage')
    op.create_table('role_api_scope',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('api_scope_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['api_scope_id'], ['manage.api_scope.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['manage.role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'api_scope_id', name='role_api_scope_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_role_api_scope_api_scope_id'), 'role_api_scope', ['api_scope_id'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_role_api_scope_role_id'), 'role_api_scope', ['role_id'], unique=False, schema='manage')
    # ### end Alembic commands ###

    op.bulk_insert(
        client_table,  # type: ignore
        [
            {
            'id'  :                 "fa2518dd-5b27-4a59-b740-e96c3c79160a",
            'created_at' :          date(2023, 3, 2), 
            'name'  :               "manage",
            'client_id'  :          "client_id_manage",
            'client_secret'  :      "vFFpgc2icUTq3j5v9aPNt",
            'grant_types'  :        ["authorization_code","refresh_token","hybrid"],
            'redirect_uris'  :      [
                "http://localhost:33001/callback",
                "http://localhost:33001/callback_silent",
                "https://manage.kabart.com.tr/callback",
                "https://manage.kabart.com.tr/callback_silent"
            ],
            'application_type'  :   "web",
            'require_consent'  :    True,
            'is_system'  :          True,
            'require_pkce'  :       True,
            'level_type'  :         "FIRST_PARTY",
            },
            {
            'id'  :                 "891981ea-85ba-40bb-b150-409e339e5b65",
            'created_at' :          date(2023, 3, 2), 
            'name'  :               "workspace",
            'client_id'  :          "client_id_workspace",
            'client_secret'  :      "V5n0zmifjs8MZogT93LpK",
            'grant_types'  :        ["authorization_code","refresh_token","hybrid"],
            'redirect_uris'  :      [
                "http://localhost:33002/callback",
                "http://localhost:33002/callback_silent",
                "https://workspace.kabart.com.tr/callback",
                "https://workspace.kabart.com.tr/callback_silent"
                
            ],
            'application_type'  :   "web",
            'require_consent'  :    True,
            'is_system'  :          True,
            'require_pkce'  :       True,
            'level_type'  :         "FIRST_PARTY",
            },
            {
            'id'  :                 "858b742b-29d1-469d-87d7-9095ef0fcbf0", 
            'created_at' :          date(2023, 3, 2), 
            'name'  :               "application",
            'client_id'  :          "client_id_application",
            'client_secret'  :      "nlSL5g6ucaeDAgamcH5nP",
            'grant_types'  :        ["authorization_code","refresh_token","hybrid"],
            'redirect_uris'  :      [
                "http://localhost:30003/callback",
                "http://localhost:30003/callback_silent",
                "https://application.kabart.com.tr/callback",
                "https://application.kabart.com.tr/callback_silent"                                
            ],
            'application_type'  :   "web",
            'require_consent'  :    True,
            'is_system'  :          True,
            'require_pkce'  :       True,
            'level_type'  :         "FIRST_PARTY",
            },
        ]
    )

    op.bulk_insert(
            user_table,  # type: ignore    
            [
                {
                'id' :  '7175e67d-0ddc-4c96-a167-c3f3ef72de5a',
                'created_at' :          date(2023, 3, 2), 
                'subject_id' : '7175e67d-0ddc-4c96-a167-c3f3ef72de5a',
                'source' :'local',
                'name' : 'admin',
                'surname' : 'admin',
                'email' : 'admin@admin.com',
                'password' : '$2b$12$xI.AJo0Es4jrgsDopMm5qOdXn4of6KsJNbdhPQEsDzIjXGy5jww5y',
                'email_verified' : False,
                'phone' : '05551112233',
                'blocked' :False,
                }
            ]
    )

    op.bulk_insert(
            tenant_table,  # type: ignore    
            [
                {
                        'id'  :                 '10a2238f-4d1e-4626-9f3c-799d3ef5e96d',
                        'created_at' :          date(2023, 3, 2), 
                        'name'  :               'Admin',
                        'title'  :              'Admin Tenant',
                        'session_timeout'  :    10080,
                        'user_id'  :            '7175e67d-0ddc-4c96-a167-c3f3ef72de5a',
                },
            ]
        )

    op.bulk_insert(
            tenant_user_table,  # type: ignore    
            [
                { 
                'id' :              'adcd70c8-ff17-4dda-afcc-abbf175b12d0',
                'created_at' : date(2023, 3, 2), 
                'user_id' :         '7175e67d-0ddc-4c96-a167-c3f3ef72de5a',
                'tenant' :          '10a2238f-4d1e-4626-9f3c-799d3ef5e96d',
                'role' :            'owner',
                },
            ]
        )

    op.bulk_insert(
            tenant_client_table,  # type: ignore    
            [
              {
                     'id' :            '0c0a2b44-a2b1-4f41-8d97-3ba998705409',
                     'created_at' : date(2023, 3, 2), 
                     'tenant_id' :     '10a2238f-4d1e-4626-9f3c-799d3ef5e96d',
                     'client_id' :     'fa2518dd-5b27-4a59-b740-e96c3c79160a',
                },
                {
                   'id' :             '902e2038-acd1-4736-9a5a-f45e159b2c09',
                   'created_at' : date(2023, 3, 2), 
                   'tenant_id' :      '10a2238f-4d1e-4626-9f3c-799d3ef5e96d',
                   'client_id' :      '858b742b-29d1-469d-87d7-9095ef0fcbf0',
                },
            ]
        )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manage_role_api_scope_role_id'), table_name='role_api_scope', schema='manage')
    op.drop_index(op.f('ix_manage_role_api_scope_api_scope_id'), table_name='role_api_scope', schema='manage')
    op.drop_table('role_api_scope', schema='manage')
    op.drop_index(op.f('ix_manage_client_api_scope_tenant_id'), table_name='client_api_scope', schema='manage')
    op.drop_index(op.f('ix_manage_client_api_scope_client_api_id'), table_name='client_api_scope', schema='manage')
    op.drop_index(op.f('ix_manage_client_api_scope_api_scope_id'), table_name='client_api_scope', schema='manage')
    op.drop_table('client_api_scope', schema='manage')
    op.drop_index(op.f('ix_manage_tenant_user_user_id'), table_name='tenant_user', schema='manage')
    op.drop_index(op.f('ix_manage_tenant_user_tenant'), table_name='tenant_user', schema='manage')
    op.drop_table('tenant_user', schema='manage')
    op.drop_index(op.f('ix_manage_tenant_client_tenant_id'), table_name='tenant_client', schema='manage')
    op.drop_index(op.f('ix_manage_tenant_client_client_id'), table_name='tenant_client', schema='manage')
    op.drop_table('tenant_client', schema='manage')
    op.drop_table('tenant', schema='manage')
    op.drop_index(op.f('ix_manage_role_user_user_id'), table_name='role_user', schema='manage')
    op.drop_index(op.f('ix_manage_role_user_tenant_id'), table_name='role_user', schema='manage')
    op.drop_index(op.f('ix_manage_role_user_role_id'), table_name='role_user', schema='manage')
    op.drop_table('role_user', schema='manage')
    op.drop_index(op.f('ix_manage_client_api_tenant_id'), table_name='client_api', schema='manage')
    op.drop_index(op.f('ix_manage_client_api_client_id'), table_name='client_api', schema='manage')
    op.drop_index(op.f('ix_manage_client_api_api_id'), table_name='client_api', schema='manage')
    op.drop_table('client_api', schema='manage')
    op.drop_index(op.f('ix_manage_api_scope_tenant_id'), table_name='api_scope', schema='manage')
    op.drop_table('api_scope', schema='manage')
    op.drop_index(op.f('ix_manage_user_subject_id'), table_name='user', schema='manage')
    op.drop_index(op.f('ix_manage_user_email'), table_name='user', schema='manage')
    op.drop_table('user', schema='manage')
    op.drop_index(op.f('ix_manage_role_tenant_id'), table_name='role', schema='manage')
    op.drop_index(op.f('ix_manage_role_name'), table_name='role', schema='manage')
    op.drop_table('role', schema='manage')
    op.drop_index(op.f('ix_manage_profile_adaptor_tenant_id'), table_name='profile_adaptor', schema='manage')
    op.drop_table('profile_adaptor', schema='manage')
    op.drop_index(op.f('ix_manage_invitation_user_id'), table_name='invitation', schema='manage')
    op.drop_index(op.f('ix_manage_invitation_tenant_id'), table_name='invitation', schema='manage')
    op.drop_table('invitation', schema='manage')
    op.drop_index(op.f('ix_manage_client_client_id'), table_name='client', schema='manage')
    op.drop_table('client', schema='manage')
    op.drop_index(op.f('ix_manage_api_tenant_id'), table_name='api', schema='manage')
    op.drop_table('api', schema='manage')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS manage")