"""first_party_api

Revision ID: 00000005
Revises: 00000004
Create Date: 2023-07-20 09:36:01.018523

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy import Table, MetaData

from mapa.manage.api.api_entity import ApiEntity
from mapa.manage.api_scope.api_scope_entity import ApiScopeEntity
from mapa.manage.client_api.client_api_entity import ClientApiEntity

# revision identifiers, used by Alembic.
revision = '00000005'
down_revision = '00000004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
    op.bulk_insert(
        ApiEntity.__table__,  # type: ignore
        [
            {
                "id": "fe379bb7-2275-4b29-823b-da8a616b2cbe",
                "created_at": "2023-07-14T11:22:39.19353",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "Workspace Api",
                "identifier": "https://workspace",
                "allow_offline_access": False,
                "skip_consent_for_verifiable_first_party_clients": None,
                "token_lifetime": 72000,
                "token_lifetime_for_web": 72800,
                "signing_alg": "RS256",
                "is_system": True,
                "level_type": "FIRST_PARTY"
            },
            {
                "id": "73edba71-5650-496e-92b0-a9886d47417e",
                "created_at": "2023-07-14T11:22:39.19353",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "Manage Api",
                "identifier": "https://manage",
                "allow_offline_access": False,
                "skip_consent_for_verifiable_first_party_clients": None,
                "token_lifetime": 72000,
                "token_lifetime_for_web": 72800,
                "signing_alg": "RS256",
                "is_system": True,
                "level_type": "FIRST_PARTY"
            }
        ]
    )
    op.bulk_insert(
        ClientApiEntity.__table__,  # type: ignore
        [
            {
                "id": "3f0b6536-179b-4068-bb66-bc1a32f70835",
                "created_at": "2023-03-02T00:00:00",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e",
                "client_id": "fa2518dd-5b27-4a59-b740-e96c3c79160a"
            },
            {
                "id": "1185466f-7071-4b1f-875a-a712d48cbefa",
                "created_at": "2023-03-02T00:00:00",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe",
                "client_id": "891981ea-85ba-40bb-b150-409e339e5b65"
            }
        ]
    )    
    op.bulk_insert(
        ApiScopeEntity.__table__,  # type: ignore
        [
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0d2f",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:api",
                "description": "Query of api scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "f2d3c274-5831-4b09-98a7-91a33732e3b3",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:api",
                "description": "Edit of api scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "5c8da699-ab98-43fe-ab2e-ff8213fd3f2c",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:api_scope",
                "description": "Query of api scope scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "78feab9d-2ca7-46c5-81db-d08bfef80c8e",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:api_scope",
                "description": "Edit of api scope scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "7b60b0ac-b161-4fd1-afde-72e375f0d405",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:client",
                "description": "Query of client scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "68bee7e5-ab63-40af-a3e8-99e385ff2e60",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:client",
                "description": "Edit of client scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "62b305c1-ff56-4bc1-bab4-93c1629d4249",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:client_api",
                "description": "Query of client api scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "7e75cb4b-2fe7-467f-bd1a-0c7830f7671c",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:client_api",
                "description": "Edit of client api scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "59e1e022-4cfe-4dd4-8660-1d2120d92c8b",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:client_api_scope",
                "description": "Query of client api scope scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "8075fe65-11e5-4dc5-b3c9-9b1444b80d58",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:client_api_scope",
                "description": "Edit of client api scope scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "adb59a5d-f89e-4822-b296-611840a4445a",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:invitation",
                "description": "Query of invitation scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "4605207b-c7ed-43f6-9735-9fe2ce8a2973",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:invitation",
                "description": "Edit of invitation scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "56c9cd3e-04fc-4b0a-8254-c39bc628cfc2",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:profile_adaptor",
                "description": "Query of profile adaptor scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "f6174e2c-4800-4ad4-b38b-57c941d47492",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:profile_adaptor",
                "description": "Edit of profile adaptor scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "ae472168-b4cb-4f77-88c7-b8e32d3c9d18",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:role",
                "description": "Query of role scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "e3780120-df3f-490d-87cf-3f029ded905f",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:role",
                "description": "Edit of role scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "1bed7a60-e9ae-4815-98f1-7b40571f7112",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:role_api_scope",
                "description": "Query of role api scope scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "e2274846-a376-4688-97f7-58831e093709",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:role_api_scope",
                "description": "Edit of role api scope scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "3cf37e93-922b-457a-8103-7aca3d6bde17",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:role_user",
                "description": "Query of role user scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "a3b0be64-21b3-44be-94af-35ffeac92bf5",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:role_user",
                "description": "Edit of role user scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "c8d889f6-217e-4cac-85d2-86640533e0e3",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:user",
                "description": "Query of user scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "6ed15314-2b4d-4243-a893-a0ccb808c0cf",
                "created_at": "2023-07-20T10:16:22.852127",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:user",
                "description": "Edit of user scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "56f3bb39-7b33-4e85-9760-b7f66058fa23",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:application",
                "description": "Query of application scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "e6183b60-36ee-44aa-a5c8-f16e4f5ef86c",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:application",
                "description": "Edit of application scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "27a0562d-3107-443b-8110-43cb64660a74",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:content_page",
                "description": "Query of content_page scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "98654445-a20a-43b7-ac73-14e24f007895",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:content_page",
                "description": "Edit of content_page scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "496712a2-ab9a-4f16-ae84-a86a73e1cb44",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:content_page_template",
                "description": "Query of content_page_template scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "cc7ff110-03c0-4a74-8a64-c088bb5400b5",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:content_page_template",
                "description": "Edit of content_page_template scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "4ffc07d3-7e92-43ea-8a4c-f12075f73321",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:connection_info",
                "description": "Query of connection_info scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "cd4ce793-7299-4c2d-98f3-be9b20c94d48",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:connection_info",
                "description": "Edit of connection_info scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "7fb5ac46-7e8b-4453-b8d8-c67d6b1cb688",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:context_var",
                "description": "Query of context_var scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "fa943102-4913-4d06-9791-353671c63c07",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:context_var",
                "description": "Edit of context_var scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "006add03-c440-4567-ac6a-1ed2c9e72fbd",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:gateway_api",
                "description": "Query of gateway_api scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "23e1e3fd-a2ce-4673-8ec9-9616a43a2b5f",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:gateway_api",
                "description": "Edit of gateway_api scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "84ecd666-635f-4b8c-86cf-bfca5e7aae76",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:integration",
                "description": "Query of integration scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "1d00d64a-23d4-41dc-9484-e4cee1020adf",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:integration",
                "description": "Edit of integration scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "cfcf853c-a390-4dd2-b534-0053e42cb0e7",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:parameter_mapping",
                "description": "Query of parameter_mapping scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "2131ab7f-1981-46f3-801d-7513b1990cca",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:parameter_mapping",
                "description": "Edit of parameter_mapping scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "30f95b14-7faf-45dc-b213-db2daad2b5e3",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:route",
                "description": "Query of route scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "05b3579b-c8d8-418a-b500-19444408d498",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:route",
                "description": "Edit of route scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "235e7746-e7b8-407c-be4e-edf3ae6e62b8",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:base_layer",
                "description": "Query of base_layer scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "e8bd5cfb-a16a-4801-a04c-7327ebe554a9",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:base_layer",
                "description": "Edit of base_layer scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "feed0eef-58c4-42a8-9408-7bfe636f55de",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:bookmark",
                "description": "Query of bookmark scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "ea0e1bf1-34d6-4638-8294-57165c080ad7",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:bookmark",
                "description": "Edit of bookmark scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "4d021e3d-e632-4ff6-9d02-59e44288040e",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:connection",
                "description": "Query of connection scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "da959cb0-3a83-4484-bb50-a31b0e991408",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:connection",
                "description": "Edit of connection scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "b2487341-432c-486f-bc2a-a38cf99e57c2",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:definition",
                "description": "Query of definition scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "b0345729-672d-4030-a7c5-ef0b1cefd8e7",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:definition",
                "description": "Edit of definition scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "ab00e208-b62f-4ba5-a630-8c0b87899357",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:hook",
                "description": "Query of hook scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "a9e5dc2d-82d3-494f-a788-e7289a3b86ab",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:hook",
                "description": "Edit of hook scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "65a753c8-f1ca-4957-8423-c77841fd1f2a",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:layer",
                "description": "Query of layer scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "ed93071f-adc2-4586-8f22-40a9cadfe345",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:layer",
                "description": "Edit of layer scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "7d426804-2feb-4b0c-a98e-8a6b72646bb3",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:layer_definition",
                "description": "Query of layer_definition scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "c99161a5-20b3-440c-9e70-d1f0cfa812e1",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:layer_definition",
                "description": "Edit of layer_definition scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "a4c89600-9723-4d83-a250-8b327e8f144d",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:layer_hook",
                "description": "Query of layer_hook scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "4c946e1a-29e1-4bdf-a871-2cf1c7d58646",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:layer_hook",
                "description": "Edit of layer_hook scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "3a69f698-f981-425e-8aa0-9fc34b84e175",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:map",
                "description": "Query of map scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "c14a4098-38d4-4ce2-9ac1-70b72160aa2a",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:map",
                "description": "Edit of map scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "9b27f7ca-3864-4db5-9271-99fb51a04310",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:map_base_layer",
                "description": "Query of map_base_layer scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "8d4bf36e-a8f1-4f57-8fd4-334801c952c0",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:map_base_layer",
                "description": "Edit of map_base_layer scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "3de9b2d2-eb0d-4898-a94b-5617ba9c11ca",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:map_layer",
                "description": "Query of map_layer scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "f122d75d-b984-40e0-8bb0-5b08b52e7636",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:map_layer",
                "description": "Edit of map_layer scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "2114f43d-6f9b-49ca-9a21-44b1b98f264a",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:namespace",
                "description": "Query of namespace scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "cc92305f-ee08-4025-8111-554777d5a4fa",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:namespace",
                "description": "Edit of namespace scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "2479a9da-9bda-4eda-bcef-08e7e7be59c4",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:reference",
                "description": "Query of reference scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "820462c1-828b-40e3-b422-65f09d5c67d1",
                "created_at": "2023-07-20T10:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:reference",
                "description": "Edit of reference scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            }
        ]
    )    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
