"""tenant_name_uk_1

Revision ID: 00000008
Revises: 00000007
Create Date: 2023-07-28 19:10:45.926954

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000008'
down_revision = '00000007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tenant_uk_1', 'tenant', ['name'], schema='manage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenant_uk_1', 'tenant', schema='manage', type_='unique')
    # ### end Alembic commands ###
