"""multi_tenant

Revision ID: 00000004
Revises: 00000003
Create Date: 2023-07-09 20:18:21.418475

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from mapa.core.data.base_entity import NULL_TENANT_ID


# revision identifiers, used by Alembic.
revision = '00000004'
down_revision = '00000003'
branch_labels = None
depends_on = None

table_list = [
    "api",
    "profile_adaptor",
    "role",
    "api_scope",
    "client_api",
    "role_user",
    #"tenant_client",
    #"tenant_user",
    "client_api_scope",
    "role_api_scope"
]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_api_scope', sa.Column('tenant_id', sa.Uuid(), nullable=True), schema='manage')
    op.create_index(op.f('ix_manage_role_api_scope_tenant_id'), 'role_api_scope', ['tenant_id'], unique=False, schema='manage')
    op.add_column('tenant_user', sa.Column('tenant_id', sa.Uuid(), nullable=True), schema='manage')
    op.drop_index('ix_manage_tenant_user_tenant', table_name='tenant_user', schema='manage')
    op.create_index(op.f('ix_manage_tenant_user_tenant_id'), 'tenant_user', ['tenant_id'], unique=False, schema='manage')
    #tenant_id'ler kaybolmaması için manuel eklendi
    op.execute('UPDATE manage.tenant_user SET tenant_id=tenant')
    #tenant_id'ler kaybolmaması için manuel eklendi
    op.drop_column('tenant_user', 'tenant', schema='manage')
    # ### end Alembic commands ###
    
    # tenant_isolation
    execute_tenant_isolation("manage", table_list, enable=True)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_user', sa.Column('tenant', sa.UUID(), autoincrement=False, nullable=False), schema='manage')
    op.drop_index(op.f('ix_manage_tenant_user_tenant_id'), table_name='tenant_user', schema='manage')
    op.create_index('ix_manage_tenant_user_tenant', 'tenant_user', ['tenant'], unique=False, schema='manage')
    #tenant_id'ler kaybolmaması için manuel eklendi
    op.execute('UPDATE manage.tenant_user SET tenant=tenant_id')
    #tenant_id'ler kaybolmaması için manuel eklendi
    op.drop_column('tenant_user', 'tenant_id', schema='manage')
    op.drop_index(op.f('ix_manage_role_api_scope_tenant_id'), table_name='role_api_scope', schema='manage')
    op.drop_column('role_api_scope', 'tenant_id', schema='manage')
    # ### end Alembic commands ###

    # tenant_isolation
    down_list = table_list.copy()
    down_list.reverse()
    execute_tenant_isolation("manage", down_list, enable=False)


def execute_tenant_isolation(schema, tables, enable):
    for table in tables:
        full_name = f"{schema}.{table}"
        if enable:
            op.execute( f"alter table {full_name} enable row level security")
            op.execute( f"create policy tenant_isolation_insert on {full_name} "
                        f"for INSERT "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_select on {full_name} "
                        f"for SELECT "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text) OR ((tenant_id)::text = '{str(NULL_TENANT_ID)}'))"
                        )
            op.execute( f"create policy tenant_isolation_update on {full_name} "
                        f"for UPDATE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text)) "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_delete on {full_name} "
                        f"for DELETE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text))"
                        )
        else:
            op.execute(f"drop policy tenant_isolation_insert on {full_name}")
            op.execute(f"drop policy tenant_isolation_select on {full_name}")
            op.execute(f"drop policy tenant_isolation_update on {full_name}")
            op.execute(f"drop policy tenant_isolation_delete on {full_name}")
            op.execute(f"alter table {full_name} disable row level security")