"""add_table_user_variable_type

Revision ID: 00000015
Revises: 00000014
Create Date: 2024-11-22 13:02:43.001544

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func
from sqlalchemy import (JSON,Uuid,Text,DateTime,Boolean)
from mapa.manage.api_scope.api_scope_entity import ApiScopeEntity
from mapa.manage.role_api_scope.role_api_scope_entity import RoleApiScopeEntity
from mapa.core.data.base_entity import NULL_TENANT_ID


# revision identifiers, used by Alembic.
revision = '00000015'
down_revision = '00000014'
branch_labels = None
depends_on = None


delete_role_api_scope_list = [
    "38a72b9c-de84-4d4a-afbe-aa79e35c92da",
    "a2b81530-b915-42dc-b3cc-f5a6ecdc46a9",
]

delete_api_scope_list = [
    "f59eaad4-c728-478d-8877-e437188d2b44",
    "d8d311fe-1aa4-4d0e-af70-08060573f156",
]

table_list = [
    "user_variable_type"
]



def upgrade() -> None:
    
    # user_variable_type tabloları için scope tanımları
    op.bulk_insert(
        ApiScopeEntity.__table__,  # type: ignore
        [
            {
                "id": "f59eaad4-c728-478d-8877-e437188d2b44",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:user_variable_type",
                "description": "Query of User Variable Type",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "d8d311fe-1aa4-4d0e-af70-08060573f156",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:user_variable_type",
                "description": "Edit of User Variable Type",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            }
        ]
    )   

    op.bulk_insert(
        RoleApiScopeEntity.__table__,  # type: ignore
        [
             {
                "id": "38a72b9c-de84-4d4a-afbe-aa79e35c92da",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "f59eaad4-c728-478d-8877-e437188d2b44",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "a2b81530-b915-42dc-b3cc-f5a6ecdc46a9",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "d8d311fe-1aa4-4d0e-af70-08060573f156",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            }
        ]
    )
    # end of user_variable_type tabloları için scope tanımları
    
    
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_variable_type',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tenant_id', name='user_variable_type_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_user_variable_type_name'), 'user_variable_type', ['name'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_user_variable_type_tenant_id'), 'user_variable_type', ['tenant_id'], unique=False, schema='manage')
    # ### end Alembic commands ###
    
    
    # tenant_isolation
    execute_tenant_isolation("manage", table_list, enable=True)


def downgrade() -> None:
    
    # tenant_isolation
    down_list = table_list.copy()
    down_list.reverse()
    execute_tenant_isolation("manage", down_list, enable=False)
    
    
    # user_variable_type tabloları için scope tanımları kaldırılır
    role_api_scope_table = sa.Table('role_api_scope',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True))
    connection = op.get_bind()
    
    for id_ in delete_role_api_scope_list:
        connection.execute(role_api_scope_table.delete().where(role_api_scope_table.c.id == id_))
    
        
    api_scope_table = sa.Table('api_scope',
        sa.MetaData(schema='manage'),
        sa.Column('id', Uuid(), primary_key=True))
    connection = op.get_bind()
    
    for id_ in delete_api_scope_list:
        connection.execute(api_scope_table.delete().where(api_scope_table.c.id == id_))
    # end of user_variable_type tabloları için scope tanımları kaldırılır
    
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manage_user_variable_type_tenant_id'), table_name='user_variable_type', schema='manage')
    op.drop_index(op.f('ix_manage_user_variable_type_name'), table_name='user_variable_type', schema='manage')
    op.drop_table('user_variable_type', schema='manage')
    # ### end Alembic commands ###



def execute_tenant_isolation(schema, tables, enable):
    for table in tables:
        full_name = f"{schema}.{table}"
        if enable:
            op.execute( f"alter table {full_name} enable row level security")
            op.execute( f"create policy tenant_isolation_insert on {full_name} "
                        f"for INSERT "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_select on {full_name} "
                        f"for SELECT "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text) OR ((tenant_id)::text = '{str(NULL_TENANT_ID)}'))"
                        )
            op.execute( f"create policy tenant_isolation_update on {full_name} "
                        f"for UPDATE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text)) "
                        f"WITH CHECK (current_setting('app.tenant_id') is not null and (select true from (select pg_typeof(uuid(current_setting('app.tenant_id')))::text as typ) s where s.typ = 'uuid'))"
                        )
            op.execute( f"create policy tenant_isolation_delete on {full_name} "
                        f"for DELETE "
                        f"using  ((current_setting('app.tenant_id') = tenant_id::text))"
                        )
        else:
            op.execute(f"drop policy tenant_isolation_insert on {full_name}")
            op.execute(f"drop policy tenant_isolation_select on {full_name}")
            op.execute(f"drop policy tenant_isolation_update on {full_name}")
            op.execute(f"drop policy tenant_isolation_delete on {full_name}")
            op.execute(f"alter table {full_name} disable row level security")