"""tenant id güncellemesi

Revision ID: 00000002
Revises: 00000001
Create Date: 2023-03-05 12:20:13.710235

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00000002'
down_revision = '00000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api', 'tenant_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='manage')
    op.drop_constraint('api_uk_1', 'api', schema='manage', type_='unique')
    op.create_unique_constraint('api_uk_1', 'api', ['identifier', 'tenant_id'], schema='manage')
    op.drop_constraint('api_scope_uk_1', 'api_scope', schema='manage', type_='unique')
    op.create_unique_constraint('api_scope_uk_1', 'api_scope', ['name', 'api_id'], schema='manage')
    op.add_column('invitation', sa.Column('tenant', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True), schema='manage')
    op.add_column('invitation', sa.Column('used', sa.Boolean(), nullable=False), schema='manage')
    op.drop_index('ix_manage_invitation_tenant_id', table_name='invitation', schema='manage')
    op.create_index(op.f('ix_manage_invitation_tenant'), 'invitation', ['tenant'], unique=False, schema='manage')
    op.drop_column('invitation', 'tenant_id', schema='manage')
    op.drop_column('invitation', 'client_id', schema='manage')
    op.alter_column('role', 'tenant_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='manage')
    op.drop_index('ix_manage_role_name', table_name='role', schema='manage')
    op.create_index(op.f('ix_manage_role_name'), 'role', ['name'], unique=False, schema='manage')
    op.create_unique_constraint('role_uk_1', 'role', ['name', 'tenant_id'], schema='manage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_uk_1', 'role', schema='manage', type_='unique')
    op.drop_index(op.f('ix_manage_role_name'), table_name='role', schema='manage')
    op.create_index('ix_manage_role_name', 'role', ['name'], unique=False, schema='manage')
    op.alter_column('role', 'tenant_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               schema='manage')
    op.add_column('invitation', sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=False), schema='manage')
    op.add_column('invitation', sa.Column('tenant_id', postgresql.UUID(), autoincrement=False, nullable=True), schema='manage')
    op.drop_index(op.f('ix_manage_invitation_tenant'), table_name='invitation', schema='manage')
    op.create_index('ix_manage_invitation_tenant_id', 'invitation', ['tenant_id'], unique=False, schema='manage')
    op.drop_column('invitation', 'used', schema='manage')
    op.drop_column('invitation', 'tenant', schema='manage')
    op.drop_constraint('api_scope_uk_1', 'api_scope', schema='manage', type_='unique')
    op.create_unique_constraint('api_scope_uk_1', 'api_scope', ['name'], schema='manage')
    op.drop_constraint('api_uk_1', 'api', schema='manage', type_='unique')
    op.create_unique_constraint('api_uk_1', 'api', ['identifier'], schema='manage')
    op.alter_column('api', 'tenant_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               schema='manage')
    # ### end Alembic commands ###
