"""first_party_api

Revision ID: 00000021
Revises: 00000020
Create Date: 2025-08-20 16:20:01.018523 

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy import Table, MetaData

from mapa.manage.api.api_entity import ApiEntity
from mapa.manage.api_scope.api_scope_entity import ApiScopeEntity
from mapa.manage.client_api.client_api_entity import ClientApiEntity

# revision identifiers, used by Alembic.
revision = '00000021'
down_revision = '00000020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.bulk_insert(
        ApiScopeEntity.__table__,  # type: ignore
        [
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0133",
                "created_at": "2025-08-20T16:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:file_store",
                "description": "Query of file store scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0134",
                "created_at": "2025-08-20T16:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:file_store",
                "description": "Edit of file store scope",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0135",
                "created_at": "2025-08-20T16:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:file_store",
                "description": "Query of file store scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            },
            {
                "id": "932a5e98-0003-4c46-aa03-770679bd0136",
                "created_at": "2025-08-20T16:20:07.733771",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:file_store",
                "description": "Edit of file store scope",
                "api_id": "fe379bb7-2275-4b29-823b-da8a616b2cbe"
            }
        ]
    )    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
