"""ldap_server conn user

Revision ID: 00000018
Revises: 00000017
Create Date: 2025-01-23 14:12:15.737266

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000018'
down_revision = '00000017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_ldap_user', sa.Boolean(), nullable=True, default=False), schema='manage')
    op.add_column('user', sa.Column('ldap_server_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True), schema='manage')
    op.create_foreign_key(None, 'user', 'ldap_server', ['ldap_server_id'], ['id'], source_schema='manage', referent_schema='manage', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='manage', type_='foreignkey')
    op.drop_column('user', 'ldap_server_id', schema='manage')
    op.drop_column('user', 'is_ldap_user', schema='manage')
    # ### end Alembic commands ###
