"""ldap_server scope

Revision ID: 00000019
Revises: 00000018
Create Date: 2025-01-23 14:33:08.167318

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func
from sqlalchemy import (JSON,Uuid,Text,DateTime,Boolean)
from mapa.manage.api_scope.api_scope_entity import ApiScopeEntity
from mapa.manage.role_api_scope.role_api_scope_entity import RoleApiScopeEntity
from mapa.core.data.base_entity import NULL_TENANT_ID

# revision identifiers, used by Alembic.
revision = '00000019'
down_revision = '00000018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    
    # ldap_server tabloları için scope tanımları
    op.bulk_insert(
        ApiScopeEntity.__table__,  # type: ignore
        [
            {
                "id": "e2a133ac-c728-478d-8877-a9886d47417e",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "query:ldap_server",
                "description": "Query of Ldap Server",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            },
            {
                "id": "a1e133ac-c728-4d0e-8877-08060573f156",
                "created_at": "2024-02-23T10:37:42.378679",
                "tenant_id": "00000000-0000-0000-0000-000000000000",
                "name": "edit:ldap_server",
                "description": "Edit of Ldap Server",
                "api_id": "73edba71-5650-496e-92b0-a9886d47417e"
            }
        ]
    )   

    op.bulk_insert(
        RoleApiScopeEntity.__table__,  # type: ignore
        [
             {
                "id": "df460aeb-6162-450d-812a-dd14e32ba522",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "e2a133ac-c728-478d-8877-a9886d47417e",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "821e4ed2-7d2d-4915-90a5-b76a8d72d3d4",
                "created_at": "2024-02-23T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "a1e133ac-c728-4d0e-8877-08060573f156",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            }
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
