"""user_add_column_context

Revision ID: 00000016
Revises: 00000015
Create Date: 2024-11-24 09:04:53.414618

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000016'
down_revision = '00000015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('context', sa.JSON(), nullable=True), schema='manage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'context', schema='manage')
    # ### end Alembic commands ###
