"""role_user_api_scope

Revision ID: 00000006
Revises: 00000005
Create Date: 2023-07-26 11:00:44.796941

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


from mapa.manage.role.role_entity import RoleEntity
from mapa.manage.role_user.role_user_entity import RoleUserEntity
from mapa.manage.role_api_scope.role_api_scope_entity import RoleApiScopeEntity

# revision identifiers, used by Alembic.
revision = '00000006'
down_revision = '00000005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        RoleEntity.__table__,  # type: ignore
        [
            {
                "id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "created_at": "2023-07-26T10:22:21.847768",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d",
                "name": "Admin",
                "description": "Admin Role"
            }
        ]
    )
    op.bulk_insert(
        RoleUserEntity.__table__,  # type: ignore
        [
            {
                "id": "d4316096-dd57-4bb4-ab83-5fec74db5b7f",
                "created_at": "2023-07-26T10:31:36.379198",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d",
                "expired_at": "2999-07-26T10:22:21.847768",
                "user_id": "7175e67d-0ddc-4c96-a167-c3f3ef72de5a",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333"
            }
        ]
    )    
    op.bulk_insert(
        RoleApiScopeEntity.__table__,  # type: ignore
        [
            {
                "id": "acd02959-c73a-4b5b-8395-c452d69705f6",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "932a5e98-0003-4c46-aa03-770679bd0d2f",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "52d740f6-5b85-4130-98e2-418fa3363766",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "f2d3c274-5831-4b09-98a7-91a33732e3b3",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "0832f5a6-0670-43aa-b5fa-cd4055930dcc",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "5c8da699-ab98-43fe-ab2e-ff8213fd3f2c",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "3a9bb0f5-5520-4629-bc7c-d945d11c7554",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "78feab9d-2ca7-46c5-81db-d08bfef80c8e",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "a3b4a401-17d6-4248-b7ce-35c676699a89",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "7b60b0ac-b161-4fd1-afde-72e375f0d405",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "e82fa3e2-58d9-4fc5-9e06-8e73b7e6d84e",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "68bee7e5-ab63-40af-a3e8-99e385ff2e60",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "91dc64c3-a9c4-4783-b5db-e5893d86b075",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "62b305c1-ff56-4bc1-bab4-93c1629d4249",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "fa19c08f-3405-40fe-b1b5-fcec71bfffa5",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "7e75cb4b-2fe7-467f-bd1a-0c7830f7671c",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "5d8a70d9-0a4f-455c-947d-962ba626503d",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "59e1e022-4cfe-4dd4-8660-1d2120d92c8b",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "f651fe34-f23c-43f2-9740-5df7945d22fc",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "8075fe65-11e5-4dc5-b3c9-9b1444b80d58",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "28656103-2c88-48b1-851a-e9738e0bb05a",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "adb59a5d-f89e-4822-b296-611840a4445a",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "af613c87-caf5-44e7-be92-38aa966091fb",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "4605207b-c7ed-43f6-9735-9fe2ce8a2973",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "dec66470-d825-478b-b438-8858e7850a24",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "56c9cd3e-04fc-4b0a-8254-c39bc628cfc2",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "b96590ac-353d-4430-87f3-fa61ab67862c",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "f6174e2c-4800-4ad4-b38b-57c941d47492",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "d436c6fe-bb89-4b6f-8d29-872129d9c772",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "ae472168-b4cb-4f77-88c7-b8e32d3c9d18",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "1700299f-0a00-44f1-a19b-6b61f04b7e20",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "e3780120-df3f-490d-87cf-3f029ded905f",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "994dc432-a739-4fab-b828-fb80f552aa3f",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "1bed7a60-e9ae-4815-98f1-7b40571f7112",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "8d26be95-d674-4bd6-936c-cdca88000fdb",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "e2274846-a376-4688-97f7-58831e093709",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "26e4e0f9-bcfc-4ab7-a54b-a2feb22b5ae1",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "3cf37e93-922b-457a-8103-7aca3d6bde17",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "05bc2e3d-71b8-4610-9c7d-0caf645f8655",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "a3b0be64-21b3-44be-94af-35ffeac92bf5",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },     
            {
                "id": "82d153ee-9f84-45cb-bb66-bdd598358f32",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "c8d889f6-217e-4cac-85d2-86640533e0e3",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "5dc94efc-3c43-490d-89ea-daac3547efff",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "6ed15314-2b4d-4243-a893-a0ccb808c0cf",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "afd80628-3766-4b61-baca-4d2d9e984d19",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "56f3bb39-7b33-4e85-9760-b7f66058fa23",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "1c901616-a6fc-4c12-a10c-6b30f33146fa",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "e6183b60-36ee-44aa-a5c8-f16e4f5ef86c",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "a0aff616-1dc0-4c3c-ad54-05b313bfe6d8",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "27a0562d-3107-443b-8110-43cb64660a74",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "513870d1-d77b-41e9-8461-a4965c0fb4fe",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "98654445-a20a-43b7-ac73-14e24f007895",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "849d7726-e68e-4f6c-9899-53837844cd71",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "496712a2-ab9a-4f16-ae84-a86a73e1cb44",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "aadf99f1-dbb1-4d33-bab4-2ac4c736c845",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "cc7ff110-03c0-4a74-8a64-c088bb5400b5",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },           
            {
                "id": "9eae329e-f174-46b3-97c2-d5aa4510a5b0",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "4ffc07d3-7e92-43ea-8a4c-f12075f73321",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "a7d917a4-4dc1-476d-9c9a-a98747bd0043",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "cd4ce793-7299-4c2d-98f3-be9b20c94d48",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "588a2774-0bed-49f5-acd5-8c708143cafe",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "7fb5ac46-7e8b-4453-b8d8-c67d6b1cb688",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "db73fdbe-c1d4-4425-b8ee-85d1ab2f9b56",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "fa943102-4913-4d06-9791-353671c63c07",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "3d905456-fedf-4573-967d-27b13a41c7da",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "006add03-c440-4567-ac6a-1ed2c9e72fbd",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "00eab00b-db23-406d-94ae-86e4a4521e1c",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "23e1e3fd-a2ce-4673-8ec9-9616a43a2b5f",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "b88525cf-9149-4c17-8b6e-810c78b37208",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "84ecd666-635f-4b8c-86cf-bfca5e7aae76",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "01875f6d-7b15-4f6a-85f7-fb9a361e5266",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "1d00d64a-23d4-41dc-9484-e4cee1020adf",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "da719512-3bdf-40e9-9c83-f230bf10e802",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "cfcf853c-a390-4dd2-b534-0053e42cb0e7",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "52e6ef8b-d7b2-4454-a86e-4e51a542fcd2",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "2131ab7f-1981-46f3-801d-7513b1990cca",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "9694a693-d7ba-4ecd-aed3-04039c1c92ec",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "30f95b14-7faf-45dc-b213-db2daad2b5e3",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "471941c5-b68a-487b-9c71-7c90ec54ab6e",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "05b3579b-c8d8-418a-b500-19444408d498",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "9baa31b7-2f8c-4cf3-8640-4c10b01ffa16",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "235e7746-e7b8-407c-be4e-edf3ae6e62b8",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "2f761150-7e77-402e-84df-339a8909c2ed",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "e8bd5cfb-a16a-4801-a04c-7327ebe554a9",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "21a2a22e-1b80-4f89-bbf1-77cd8587fae2",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "feed0eef-58c4-42a8-9408-7bfe636f55de",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "b365ac31-872c-4dd7-a351-a73d94daa1c6",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "ea0e1bf1-34d6-4638-8294-57165c080ad7",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "66f488de-08cb-4bf6-9eb7-eaacb9f819c7",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "4d021e3d-e632-4ff6-9d02-59e44288040e",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "156d71e0-5c42-467a-8df2-be8f6d5bbdc2",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "da959cb0-3a83-4484-bb50-a31b0e991408",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "b4101f6d-218e-4063-a85f-e072cb5887e0",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "b2487341-432c-486f-bc2a-a38cf99e57c2",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "bd9d0297-cb49-4fe8-b5be-e6644b84317f",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "b0345729-672d-4030-a7c5-ef0b1cefd8e7",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "014eb8df-1cd4-422d-92d2-d5f152b10113",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "ab00e208-b62f-4ba5-a630-8c0b87899357",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "6e891a21-1a57-4558-b683-5e6d7f91ed9a",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "a9e5dc2d-82d3-494f-a788-e7289a3b86ab",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "94718f69-93c3-4cf7-b205-37213c5aa025",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "65a753c8-f1ca-4957-8423-c77841fd1f2a",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "94cb8ffe-8b5d-4d12-a311-b39513820a8a",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "ed93071f-adc2-4586-8f22-40a9cadfe345",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "56c4ef99-c74d-4746-8f26-ea8f7e5f2cc2",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "7d426804-2feb-4b0c-a98e-8a6b72646bb3",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "a96e9bc3-6238-4469-bb3b-5194175ad12f",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "c99161a5-20b3-440c-9e70-d1f0cfa812e1",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "36e950ad-19d4-4249-955a-389eda493315",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "a4c89600-9723-4d83-a250-8b327e8f144d",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "811368e6-cd4c-47ae-81df-35c4e1962f5b",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "4c946e1a-29e1-4bdf-a871-2cf1c7d58646",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "e9d66962-115b-48e0-a250-722f0fb6f416",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "3a69f698-f981-425e-8aa0-9fc34b84e175",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "cfc667b4-373d-41ea-8ac6-5537ba48bc9a",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "c14a4098-38d4-4ce2-9ac1-70b72160aa2a",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "77cd5223-90d8-4356-9e99-80f414f5195d",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "9b27f7ca-3864-4db5-9271-99fb51a04310",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "ddc36de3-c9da-4c58-a98f-b19cc9acbdc3",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "8d4bf36e-a8f1-4f57-8fd4-334801c952c0",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "4f060437-4ac5-41ec-ae51-5fffedb18a09",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "3de9b2d2-eb0d-4898-a94b-5617ba9c11ca",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "28d40e52-60e2-45c1-a0a6-ecf66da1d84f",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "f122d75d-b984-40e0-8bb0-5b08b52e7636",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "469735bc-c52e-4d5e-859c-95fe5a27537e",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "2114f43d-6f9b-49ca-9a21-44b1b98f264a",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "2e510a3b-28d2-4f9c-9873-c89aa3124039",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "cc92305f-ee08-4025-8111-554777d5a4fa",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "35507944-7a98-4ca5-84bd-dff7bfe5dc30",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "2479a9da-9bda-4eda-bcef-08e7e7be59c4",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            },
            {
                "id": "ac8721dc-2d61-4f8f-9cd2-9964a65413ee",
                "created_at": "2023-07-26T10:37:42.378679",
                "role_id": "b98cc0ae-5bf9-4a2b-8c94-70fb9f79f333",
                "api_scope_id": "820462c1-828b-40e3-b422-65f09d5c67d1",
                "tenant_id": "10a2238f-4d1e-4626-9f3c-799d3ef5e96d"
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
