"""search filter and base with ldap

Revision ID: 00000020
Revises: 00000019
Create Date: 2025-01-28 13:52:19.505917

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000020'
down_revision = '00000019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ldap_server', sa.Column('search_base', sa.Text(), nullable=False), schema='manage')
    op.add_column('ldap_server', sa.Column('search_filter', sa.Text(), nullable=False), schema='manage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ldap_server', 'search_filter', schema='manage')
    op.drop_column('ldap_server', 'search_base', schema='manage')
    # ### end Alembic commands ###
