"""ldap_server

Revision ID: 00000017
Revises: 00000016
Create Date: 2025-01-23 14:05:48.014308

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000017'
down_revision = '00000016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ldap_server',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('get_info', sa.Text(), nullable=False),
    sa.Column('authentication', sa.Text(), nullable=False),
    sa.Column('auto_bind', sa.Text(), nullable=False),
    sa.Column('attribute_map', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tenant_id', name='ldap_uk_1'),
    schema='manage'
    )
    op.create_index(op.f('ix_manage_ldap_server_name'), 'ldap_server', ['name'], unique=False, schema='manage')
    op.create_index(op.f('ix_manage_ldap_server_tenant_id'), 'ldap_server', ['tenant_id'], unique=False, schema='manage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manage_ldap_server_tenant_id'), table_name='ldap_server', schema='manage')
    op.drop_index(op.f('ix_manage_ldap_server_name'), table_name='ldap_server', schema='manage')
    op.drop_table('ldap_server', schema='manage')
    # ### end Alembic commands ###
