"""init gateway

Revision ID: 00000001
Revises: 
Create Date: 2023-03-05 06:18:04.311004

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    
    op.execute("CREATE SCHEMA IF NOT EXISTS gateway")
    op.execute("GRANT USAGE ON SCHEMA gateway TO mapa")
    op.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA gateway GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mapa")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_connection_info_name'), 'connection_info', ['name'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_connection_info_tenant_id'), 'connection_info', ['tenant_id'], unique=False, schema='gateway')
    op.create_table('gateway_api',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('manage_api_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', name='gateway_api_uk_2'),
    sa.UniqueConstraint('name', name='gateway_api_uk_1'),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_gateway_api_manage_api_id'), 'gateway_api', ['manage_api_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_gateway_api_tenant_id'), 'gateway_api', ['tenant_id'], unique=False, schema='gateway')
    op.create_table('integration',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timeout_in_millis', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('connection', sa.JSON(), nullable=False),
    sa.Column('connection_info_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('gateway_api_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['connection_info_id'], ['gateway.connection_info.id'], ),
    sa.ForeignKeyConstraint(['gateway_api_id'], ['gateway.gateway_api.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_api_id', 'name', name='integration_uk_1'),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_integration_connection_info_id'), 'integration', ['connection_info_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_integration_gateway_api_id'), 'integration', ['gateway_api_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_integration_tenant_id'), 'integration', ['tenant_id'], unique=False, schema='gateway')

    op.create_table('route',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method_type', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('gateway_api_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('integration_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['gateway_api_id'], ['gateway.gateway_api.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['gateway.integration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_api_id', 'path', 'method_type', name='route_uk_1'),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_route_gateway_api_id'), 'route', ['gateway_api_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_route_integration_id'), 'route', ['integration_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_route_tenant_id'), 'route', ['tenant_id'], unique=False, schema='gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gateway_route_tenant_id'), table_name='route', schema='gateway')
    op.drop_index(op.f('ix_gateway_route_integration_id'), table_name='route', schema='gateway')
    op.drop_index(op.f('ix_gateway_route_gateway_api_id'), table_name='route', schema='gateway')
    op.drop_table('route', schema='gateway')

    op.drop_index(op.f('ix_gateway_integration_tenant_id'), table_name='integration', schema='gateway')
    op.drop_index(op.f('ix_gateway_integration_gateway_api_id'), table_name='integration', schema='gateway')
    op.drop_index(op.f('ix_gateway_integration_connection_info_id'), table_name='integration', schema='gateway')
    op.drop_table('integration', schema='gateway')
    op.drop_index(op.f('ix_gateway_gateway_api_tenant_id'), table_name='gateway_api', schema='gateway')
    op.drop_index(op.f('ix_gateway_gateway_api_manage_api_id'), table_name='gateway_api', schema='gateway')
    op.drop_table('gateway_api', schema='gateway')
    op.drop_index(op.f('ix_gateway_connection_info_tenant_id'), table_name='connection_info', schema='gateway')
    op.drop_index(op.f('ix_gateway_connection_info_name'), table_name='connection_info', schema='gateway')
    op.drop_table('connection_info', schema='gateway')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS gateway")