"""route add column query

Revision ID: 00000003
Revises: 00000002
Create Date: 2023-03-08 07:13:55.146796

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000003'
down_revision = '00000002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('query', sa.Text(), nullable=True), schema='gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'query', schema='gateway')
    # ### end Alembic commands ###
