"""route_set_null_fk

Revision ID: 00000006
Revises: 00000005
Create Date: 2023-08-07 12:41:09.320996

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000006'
down_revision = '00000005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('route_integration_id_fkey', 'route', schema='gateway', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'integration', ['integration_id'], ['id'], source_schema='gateway', referent_schema='gateway', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', schema='gateway', type_='foreignkey')
    op.create_foreign_key('route_integration_id_fkey', 'route', 'integration', ['integration_id'], ['id'], source_schema='gateway', referent_schema='gateway', ondelete='CASCADE')
    # ### end Alembic commands ###
