"""gateway api context variables

Revision ID: 00000004
Revises: 00000003
Create Date: 2023-05-03 16:33:22.583499

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000004'
down_revision = '00000003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_var',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'tenant_id', name='gateway_context_var_key_tenant_id_uk'),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_context_var_tenant_id'), 'context_var', ['tenant_id'], unique=False, schema='gateway')
    op.add_column('gateway_api', sa.Column('context', sa.JSON(), nullable=True), schema='gateway')
    # ### end Alembic commands ###
    
    op.create_table('parameter_mapping',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('param_list', sa.JSON(), nullable=False),
    sa.Column('integration_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['gateway.integration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'type', 'status_code', name='parameter_mapping_uk_1'),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_parameter_mapping_integration_id'), 'parameter_mapping', ['integration_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_parameter_mapping_tenant_id'), 'parameter_mapping', ['tenant_id'], unique=False, schema='gateway')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gateway_api', 'context', schema='gateway')
    op.drop_index(op.f('ix_gateway_context_var_tenant_id'), table_name='context_var', schema='gateway')
    op.drop_table('context_var', schema='gateway')
    # ### end Alembic commands ###
    
    op.drop_index(op.f('ix_gateway_parameter_mapping_tenant_id'), table_name='parameter_mapping', schema='gateway')
    op.drop_index(op.f('ix_gateway_parameter_mapping_integration_id'), table_name='parameter_mapping', schema='gateway')
    op.drop_table('parameter_mapping', schema='gateway')
