"""route_add_columns

Revision ID: 00000008
Revises: 00000007
Create Date: 2025-04-30 19:28:34.035940

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000008'
down_revision = '00000007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('cache_timeout', sa.Integer(), nullable=True), schema='gateway')
    op.add_column('route', sa.Column('rate_limit', sa.Integer(), nullable=True), schema='gateway')
    op.add_column('route', sa.Column('rate_second', sa.Integer(), nullable=True), schema='gateway')
    op.add_column('route', sa.Column('retry_count', sa.Integer(), nullable=True), schema='gateway')
    op.add_column('route', sa.Column('retry_millisecond', sa.Integer(), nullable=True), schema='gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'retry_millisecond', schema='gateway')
    op.drop_column('route', 'retry_count', schema='gateway')
    op.drop_column('route', 'rate_second', schema='gateway')
    op.drop_column('route', 'rate_limit', schema='gateway')
    op.drop_column('route', 'cache_timeout', schema='gateway')
    # ### end Alembic commands ###
