"""full_logging

Revision ID: 00000010
Revises: 00000009
Create Date: 2025-06-16 12:46:09.313853

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000010'
down_revision = '00000009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('full_logging', sa.Boolean(), nullable=True), schema='gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'full_logging', schema='gateway')
    # ### end Alembic commands ###
