"""integration_add_column

Revision ID: 00000007
Revises: 00000006
Create Date: 2023-11-02 12:41:11.229860

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000007'
down_revision = '00000006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('context', sa.JSON(), nullable=True), schema='gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration', 'context', schema='gateway')
    # ### end Alembic commands ###
