"""tenant id güncellemesi

Revision ID: 00000002
Revises: 00000001
Create Date: 2023-03-05 12:26:39.196875

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00000002'
down_revision = '00000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connection_info', 'tenant_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='gateway')
    op.create_unique_constraint('connection_info_uk_1', 'connection_info', ['name', 'tenant_id'], schema='gateway')
    op.alter_column('gateway_api', 'tenant_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='gateway')
    op.drop_constraint('gateway_api_uk_1', 'gateway_api', schema='gateway', type_='unique')
    op.create_unique_constraint('gateway_api_uk_1', 'gateway_api', ['name', 'tenant_id'], schema='gateway')
    op.drop_constraint('gateway_api_uk_2', 'gateway_api', schema='gateway', type_='unique')
    op.create_unique_constraint('gateway_api_uk_2', 'gateway_api', ['identifier', 'tenant_id'], schema='gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gateway_api_uk_2', 'gateway_api', schema='gateway', type_='unique')
    op.create_unique_constraint('gateway_api_uk_2', 'gateway_api', ['identifier'], schema='gateway')
    op.drop_constraint('gateway_api_uk_1', 'gateway_api', schema='gateway', type_='unique')
    op.create_unique_constraint('gateway_api_uk_1', 'gateway_api', ['name'], schema='gateway')
    op.alter_column('gateway_api', 'tenant_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               schema='gateway')
    op.drop_constraint('connection_info_uk_1', 'connection_info', schema='gateway', type_='unique')
    op.alter_column('connection_info', 'tenant_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               schema='gateway')
    # ### end Alembic commands ###
