"""outbox pattern

Revision ID: 00000009
Revises: 00000008
Create Date: 2025-05-09 18:04:00.188182

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000009'
down_revision = '00000008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('message_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', 'DEAD_LETTERED', name='outbox_status_enum_gateway'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_outbox_tenant_id'), 'outbox', ['tenant_id'], unique=False, schema='gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gateway_outbox_tenant_id'), table_name='outbox', schema='gateway')
    op.drop_table('outbox', schema='gateway')
    # ### end Alembic commands ###
