"""jwk_token entity

Revision ID: 00000002
Revises: 00000001
Create Date: 2023-04-05 13:17:19.900522

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000002'
down_revision = '00000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwk',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=False),
    sa.Column('private_pem', sa.Text(), nullable=False),
    sa.Column('public_pem', sa.Text(), nullable=False),
    sa.Column('jwk', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sso'
    )
    op.create_index(op.f('ix_sso_jwk_key_id'), 'jwk', ['key_id'], unique=False, schema='sso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sso_jwk_key_id'), table_name='jwk', schema='sso')
    op.drop_table('jwk', schema='sso')
    # ### end Alembic commands ###
