"""init sso

Revision ID: 00000001
Revises: 
Create Date: 2023-03-02 15:54:53.698463

"""
from datetime import date
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00000001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    
    op.execute("CREATE SCHEMA IF NOT EXISTS sso")
    op.execute("GRANT USAGE ON SCHEMA sso TO mapa")
    op.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA sso GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mapa")
    
    # ### commands auto generated by Alembic - please adjust! ###
    authorization_code_table = op.create_table('authorization_code',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('user_session_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('nonce', sa.Text(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('code_challenge', sa.Text(), nullable=True),
    sa.Column('code_challenge_method', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sso'
    )
    op.create_index(op.f('ix_sso_authorization_code_code'), 'authorization_code', ['code'], unique=True, schema='sso')
    consent_table = op.create_table('consent',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sso'
    )
    op.create_index('consent_client_id_user_id', 'consent', ['client_id', 'user_id'], unique=False, schema='sso')
    op.create_table('refresh_token',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_session_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('num_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('nonce', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sso'
    )
    user_session_table = op.create_table('user_session',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('authenticated_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sso'
    )
    op.create_index(op.f('ix_sso_user_session_user_id'), 'user_session', ['user_id'], unique=False, schema='sso')
    user_session_client_table = op.create_table('user_session_client',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_session_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('client_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('tenant', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_session_id'], ['sso.user_session.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    schema='sso'
    )
    op.create_index(op.f('ix_sso_user_session_client_client_id'), 'user_session_client', ['client_id'], unique=False, schema='sso')
    op.create_index(op.f('ix_sso_user_session_client_user_session_id'), 'user_session_client', ['user_session_id'], unique=False, schema='sso')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sso_user_session_client_user_session_id'), table_name='user_session_client', schema='sso')
    op.drop_index(op.f('ix_sso_user_session_client_client_id'), table_name='user_session_client', schema='sso')
    op.drop_table('user_session_client', schema='sso')
    op.drop_index(op.f('ix_sso_user_session_user_id'), table_name='user_session', schema='sso')
    op.drop_table('user_session', schema='sso')
    op.drop_table('refresh_token', schema='sso')
    op.drop_index('consent_client_id_user_id', table_name='consent', schema='sso')
    op.drop_table('consent', schema='sso')
    op.drop_index(op.f('ix_sso_authorization_code_code'), table_name='authorization_code', schema='sso')
    op.drop_table('authorization_code', schema='sso')
    # ### end Alembic commands ###
    
    op.execute("DROP SCHEMA IF EXISTS sso")


