db:
  url: "Veritabanı bağlantı bilgileri"
oidc:
  jwks_uri: "SSO sunucusunun JWKS linki"
elk:
  host: "host.docker.internal"
  port: 5000
apm:
  service_name: "mapa-spatial"
  secret_token: ""
  server_url: "http://host.docker.internal:8200"
  environment: "mapa-spatial-service-environment"
  body: "all"
  log_level: "info"
alembic:
  migrations_path: "/home/honk/source/mapa/mapa-backend/apps/spatial/migrations"
  url: "postgresql://mapa:12345Abc.@postgres/mapa_test"
rabbitmq:
  exchange_name: "mapa-exchange"
  host: "localhost"
  port: 5672
  username: "mapa"
  password: "mapa"
  virtual_host: "/"
minio:
  endpoint: "minio:9000"
  external_endpoint: "https://storage.kabart.com.tr/:9000"
  access_key: "mapa"
  secret_key: "mapa12345"
  bucket: "mapa-spatial-files"
  secure: false
